// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cart.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createActiveCart = `-- name: CreateActiveCart :one
INSERT INTO
  carts (user_id, status, currency)
VALUES
  ($1, 'active', $2)
RETURNING
  cart_id, user_id, status, currency, created_at, updated_at
`

type CreateActiveCartParams struct {
	UserID   uuid.UUID
	Currency string
}

func (q *Queries) CreateActiveCart(ctx context.Context, arg CreateActiveCartParams) (Cart, error) {
	row := q.db.QueryRowContext(ctx, createActiveCart, arg.UserID, arg.Currency)
	var i Cart
	err := row.Scan(
		&i.CartID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCartItem = `-- name: DeleteCartItem :execrows
DELETE FROM cart_items
WHERE
  cart_id = $1
  AND sku = $2
`

type DeleteCartItemParams struct {
	CartID uuid.UUID
	Sku    string
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteCartItem, arg.CartID, arg.Sku)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getActiveCartByUserID = `-- name: GetActiveCartByUserID :one
SELECT
  cart_id, user_id, status, currency, created_at, updated_at
FROM
  carts
WHERE
  user_id = $1
  AND status = 'active'
`

func (q *Queries) GetActiveCartByUserID(ctx context.Context, userID uuid.UUID) (Cart, error) {
	row := q.db.QueryRowContext(ctx, getActiveCartByUserID, userID)
	var i Cart
	err := row.Scan(
		&i.CartID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductSnapshotBySKU = `-- name: GetProductSnapshotBySKU :one
SELECT
  sku, product_id, name, unit_price, currency, created_at, updated_at
FROM
  product_snapshots
WHERE
  sku = $1
`

func (q *Queries) GetProductSnapshotBySKU(ctx context.Context, sku string) (ProductSnapshot, error) {
	row := q.db.QueryRowContext(ctx, getProductSnapshotBySKU, sku)
	var i ProductSnapshot
	err := row.Scan(
		&i.Sku,
		&i.ProductID,
		&i.Name,
		&i.UnitPrice,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCartItem = `-- name: InsertCartItem :one
INSERT INTO
  cart_items (cart_id, sku, quantity, unit_price, currency, product_name)
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
  )
ON CONFLICT (cart_id, sku) DO UPDATE
SET
  quantity = cart_items.quantity + EXCLUDED.quantity,
  updated_at = NOW()
RETURNING
  cart_item_id, cart_id, sku, quantity, unit_price, currency, product_name, created_at, updated_at
`

type InsertCartItemParams struct {
	CartID      uuid.UUID
	Sku         string
	Quantity    int32
	UnitPrice   int64
	Currency    string
	ProductName string
}

func (q *Queries) InsertCartItem(ctx context.Context, arg InsertCartItemParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, insertCartItem,
		arg.CartID,
		arg.Sku,
		arg.Quantity,
		arg.UnitPrice,
		arg.Currency,
		arg.ProductName,
	)
	var i CartItem
	err := row.Scan(
		&i.CartItemID,
		&i.CartID,
		&i.Sku,
		&i.Quantity,
		&i.UnitPrice,
		&i.Currency,
		&i.ProductName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCartItemsByCartID = `-- name: ListCartItemsByCartID :many
SELECT
  cart_item_id, cart_id, sku, quantity, unit_price, currency, product_name, created_at, updated_at
FROM
  cart_items
WHERE
  cart_id = $1
ORDER BY
  created_at ASC
`

func (q *Queries) ListCartItemsByCartID(ctx context.Context, cartID uuid.UUID) ([]CartItem, error) {
	rows, err := q.db.QueryContext(ctx, listCartItemsByCartID, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CartItem
	for rows.Next() {
		var i CartItem
		if err := rows.Scan(
			&i.CartItemID,
			&i.CartID,
			&i.Sku,
			&i.Quantity,
			&i.UnitPrice,
			&i.Currency,
			&i.ProductName,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE cart_items
SET
  quantity = $1,
  updated_at = NOW()
WHERE
  cart_id = $2
  AND sku = $3
RETURNING
  cart_item_id, cart_id, sku, quantity, unit_price, currency, product_name, created_at, updated_at
`

type UpdateCartItemQuantityParams struct {
	Quantity int32
	CartID   uuid.UUID
	Sku      string
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRowContext(ctx, updateCartItemQuantity, arg.Quantity, arg.CartID, arg.Sku)
	var i CartItem
	err := row.Scan(
		&i.CartItemID,
		&i.CartID,
		&i.Sku,
		&i.Quantity,
		&i.UnitPrice,
		&i.Currency,
		&i.ProductName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProductSnapshot = `-- name: UpsertProductSnapshot :one
INSERT INTO
  product_snapshots (sku, product_id, name, unit_price, currency)
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5
  )
ON CONFLICT (sku) DO UPDATE
SET
  product_id = EXCLUDED.product_id,
  name = EXCLUDED.name,
  unit_price = EXCLUDED.unit_price,
  currency = EXCLUDED.currency,
  updated_at = NOW()
RETURNING
  sku, product_id, name, unit_price, currency, created_at, updated_at
`

type UpsertProductSnapshotParams struct {
	Sku       string
	ProductID uuid.NullUUID
	Name      string
	UnitPrice int64
	Currency  string
}

func (q *Queries) UpsertProductSnapshot(ctx context.Context, arg UpsertProductSnapshotParams) (ProductSnapshot, error) {
	row := q.db.QueryRowContext(ctx, upsertProductSnapshot,
		arg.Sku,
		arg.ProductID,
		arg.Name,
		arg.UnitPrice,
		arg.Currency,
	)
	var i ProductSnapshot
	err := row.Scan(
		&i.Sku,
		&i.ProductID,
		&i.Name,
		&i.UnitPrice,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
