// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Cart struct {
	CartID    uuid.UUID
	UserID    uuid.UUID
	Status    string
	Currency  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CartItem struct {
	CartItemID  uuid.UUID
	CartID      uuid.UUID
	Sku         string
	Quantity    int32
	UnitPrice   int64
	Currency    string
	ProductName string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ProductSnapshot struct {
	Sku       string
	ProductID uuid.NullUUID
	Name      string
	UnitPrice int64
	Currency  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
