// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateActiveCart(ctx context.Context, arg CreateActiveCartParams) (Cart, error)
	DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) (int64, error)
	GetActiveCartByUserID(ctx context.Context, userID uuid.UUID) (Cart, error)
	GetProductSnapshotBySKU(ctx context.Context, sku string) (ProductSnapshot, error)
	InsertCartItem(ctx context.Context, arg InsertCartItemParams) (CartItem, error)
	ListCartItemsByCartID(ctx context.Context, cartID uuid.UUID) ([]CartItem, error)
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error)
	UpsertProductSnapshot(ctx context.Context, arg UpsertProductSnapshotParams) (ProductSnapshot, error)
}

var _ Querier = (*Queries)(nil)
