// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Currency struct {
	ID       uuid.UUID
	Code     string
	Name     string
	Symbol   sql.NullString
	Decimals int32
}

type OutboxRecord struct {
	ID            uuid.UUID
	EventID       string
	EventName     string
	AggregateType string
	AggregateID   string
	Topic         string
	Key           []byte
	Payload       []byte
	Headers       json.RawMessage
	Attempt       int32
	Status        string
	LastError     string
	NextAttemptAt sql.NullTime
	LockedAt      sql.NullTime
	PublishedAt   sql.NullTime
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Product struct {
	ProductID   uuid.UUID
	Sku         string
	Name        string
	Description sql.NullString
	Price       int64
	CurrencyID  uuid.UUID
	CategoryID  uuid.NullUUID
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type StockRecord struct {
	StockRecordID uuid.UUID
	ProductID     uuid.UUID
	Quantity      int32
	Reserved      int32
	Available     sql.NullInt32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
