// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const appendOutboxRecord = `-- name: AppendOutboxRecord :one
INSERT INTO
  outbox_records (
    event_id,
    event_name,
    aggregate_type,
    aggregate_id,
    topic,
    key,
    payload,
    headers,
    attempt,
    status
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    0,
    $9
  )
RETURNING
  id, event_id, event_name, aggregate_type, aggregate_id, topic, key, payload, headers, attempt, status, last_error, next_attempt_at, locked_at, published_at, created_at, updated_at
`

type AppendOutboxRecordParams struct {
	EventID       string
	EventName     string
	AggregateType string
	AggregateID   string
	Topic         string
	Key           []byte
	Payload       []byte
	Headers       json.RawMessage
	Status        string
}

func (q *Queries) AppendOutboxRecord(ctx context.Context, arg AppendOutboxRecordParams) (OutboxRecord, error) {
	row := q.db.QueryRowContext(ctx, appendOutboxRecord,
		arg.EventID,
		arg.EventName,
		arg.AggregateType,
		arg.AggregateID,
		arg.Topic,
		arg.Key,
		arg.Payload,
		arg.Headers,
		arg.Status,
	)
	var i OutboxRecord
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventName,
		&i.AggregateType,
		&i.AggregateID,
		&i.Topic,
		&i.Key,
		&i.Payload,
		&i.Headers,
		&i.Attempt,
		&i.Status,
		&i.LastError,
		&i.NextAttemptAt,
		&i.LockedAt,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimPendingOutboxRecords = `-- name: ClaimPendingOutboxRecords :many
UPDATE outbox_records
SET
  status = 'in_progress',
  locked_at = $1,
  updated_at = $1
WHERE
  id IN (
    SELECT
      o.id
    FROM
      outbox_records AS o
    WHERE
      (
        o.status IN ('pending', 'failed')
        AND COALESCE(o.next_attempt_at, '-infinity'::timestamptz) <= $2
      )
      OR (
        o.status = 'in_progress'
        AND o.locked_at IS NOT NULL
        AND o.locked_at <= $3
      )
    ORDER BY
      o.created_at,
      o.id
    LIMIT
      $4 FOR UPDATE SKIP LOCKED
  )
RETURNING
  id, event_id, event_name, aggregate_type, aggregate_id, topic, key, payload, headers, attempt, status, last_error, next_attempt_at, locked_at, published_at, created_at, updated_at
`

type ClaimPendingOutboxRecordsParams struct {
	ClaimedAt   sql.NullTime
	Before      sql.NullTime
	StaleBefore sql.NullTime
	LimitCount  int32
}

func (q *Queries) ClaimPendingOutboxRecords(ctx context.Context, arg ClaimPendingOutboxRecordsParams) ([]OutboxRecord, error) {
	rows, err := q.db.QueryContext(ctx, claimPendingOutboxRecords,
		arg.ClaimedAt,
		arg.Before,
		arg.StaleBefore,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxRecord
	for rows.Next() {
		var i OutboxRecord
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventName,
			&i.AggregateType,
			&i.AggregateID,
			&i.Topic,
			&i.Key,
			&i.Payload,
			&i.Headers,
			&i.Attempt,
			&i.Status,
			&i.LastError,
			&i.NextAttemptAt,
			&i.LockedAt,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxRecordFailed = `-- name: MarkOutboxRecordFailed :execrows
UPDATE outbox_records
SET
  status = 'failed',
  attempt = $1,
  next_attempt_at = $2,
  last_error = $3,
  locked_at = NULL,
  updated_at = $4
WHERE
  id = $5
  AND status = 'in_progress'
  AND locked_at = $6
`

type MarkOutboxRecordFailedParams struct {
	Attempt       int32
	NextAttemptAt sql.NullTime
	LastError     string
	UpdatedAt     time.Time
	ID            uuid.UUID
	ClaimToken    sql.NullTime
}

func (q *Queries) MarkOutboxRecordFailed(ctx context.Context, arg MarkOutboxRecordFailedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOutboxRecordFailed,
		arg.Attempt,
		arg.NextAttemptAt,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markOutboxRecordPublished = `-- name: MarkOutboxRecordPublished :execrows
UPDATE outbox_records
SET
  status = 'published',
  published_at = $1,
  locked_at = NULL,
  updated_at = $1
WHERE
  id = $2
  AND status = 'in_progress'
  AND locked_at = $3
`

type MarkOutboxRecordPublishedParams struct {
	PublishedAt sql.NullTime
	ID          uuid.UUID
	ClaimToken  sql.NullTime
}

func (q *Queries) MarkOutboxRecordPublished(ctx context.Context, arg MarkOutboxRecordPublishedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOutboxRecordPublished, arg.PublishedAt, arg.ID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
