// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
WITH
  created AS (
    INSERT INTO
      products (
        sku,
        name,
        description,
        price,
        currency_id,
        category_id,
        status
      )
    VALUES
      (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7
      )
    RETURNING
      product_id, sku, name, description, price, currency_id, category_id, status, created_at, updated_at
  )
SELECT
  products.product_id, products.sku, products.name, products.description, products.price, products.currency_id, products.category_id, products.status, products.created_at, products.updated_at,
  currencies.id, currencies.code, currencies.name, currencies.symbol, currencies.decimals
FROM
  created
  JOIN products ON products.product_id = created.product_id
  LEFT JOIN currencies ON products.currency_id = currencies.id
`

type CreateProductParams struct {
	Sku         string
	Name        string
	Description sql.NullString
	Price       int64
	CurrencyID  uuid.UUID
	CategoryID  uuid.NullUUID
	Status      string
}

type CreateProductRow struct {
	Product  Product
	Currency Currency
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.CurrencyID,
		arg.CategoryID,
		arg.Status,
	)
	var i CreateProductRow
	err := row.Scan(
		&i.Product.ProductID,
		&i.Product.Sku,
		&i.Product.Name,
		&i.Product.Description,
		&i.Product.Price,
		&i.Product.CurrencyID,
		&i.Product.CategoryID,
		&i.Product.Status,
		&i.Product.CreatedAt,
		&i.Product.UpdatedAt,
		&i.Currency.ID,
		&i.Currency.Code,
		&i.Currency.Name,
		&i.Currency.Symbol,
		&i.Currency.Decimals,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :one
DELETE FROM products
WHERE
  product_id = $1
RETURNING
  product_id, sku, name, description, price, currency_id, category_id, status, created_at, updated_at
`

func (q *Queries) DeleteProduct(ctx context.Context, productID uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, deleteProduct, productID)
	var i Product
	err := row.Scan(
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.CurrencyID,
		&i.CategoryID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrencyByCode = `-- name: GetCurrencyByCode :one
SELECT
  id
FROM
  currencies
WHERE
  code = $1
`

func (q *Queries) GetCurrencyByCode(ctx context.Context, code string) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, getCurrencyByCode, code)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT
  products.product_id, products.sku, products.name, products.description, products.price, products.currency_id, products.category_id, products.status, products.created_at, products.updated_at,
  currencies.id, currencies.code, currencies.name, currencies.symbol, currencies.decimals
FROM
  products
  JOIN currencies ON products.currency_id = currencies.id
WHERE
  product_id = $1
`

type GetProductByIDRow struct {
	Product  Product
	Currency Currency
}

func (q *Queries) GetProductByID(ctx context.Context, productID uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, productID)
	var i GetProductByIDRow
	err := row.Scan(
		&i.Product.ProductID,
		&i.Product.Sku,
		&i.Product.Name,
		&i.Product.Description,
		&i.Product.Price,
		&i.Product.CurrencyID,
		&i.Product.CategoryID,
		&i.Product.Status,
		&i.Product.CreatedAt,
		&i.Product.UpdatedAt,
		&i.Currency.ID,
		&i.Currency.Code,
		&i.Currency.Name,
		&i.Currency.Symbol,
		&i.Currency.Decimals,
	)
	return i, err
}

const getProductBySKU = `-- name: GetProductBySKU :one
SELECT
  products.product_id, products.sku, products.name, products.description, products.price, products.currency_id, products.category_id, products.status, products.created_at, products.updated_at,
  currencies.id, currencies.code, currencies.name, currencies.symbol, currencies.decimals
FROM
  products
  JOIN currencies ON products.currency_id = currencies.id
WHERE
  sku = $1
`

type GetProductBySKURow struct {
	Product  Product
	Currency Currency
}

func (q *Queries) GetProductBySKU(ctx context.Context, sku string) (GetProductBySKURow, error) {
	row := q.db.QueryRowContext(ctx, getProductBySKU, sku)
	var i GetProductBySKURow
	err := row.Scan(
		&i.Product.ProductID,
		&i.Product.Sku,
		&i.Product.Name,
		&i.Product.Description,
		&i.Product.Price,
		&i.Product.CurrencyID,
		&i.Product.CategoryID,
		&i.Product.Status,
		&i.Product.CreatedAt,
		&i.Product.UpdatedAt,
		&i.Currency.ID,
		&i.Currency.Code,
		&i.Currency.Name,
		&i.Currency.Symbol,
		&i.Currency.Decimals,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT
  products.product_id, products.sku, products.name, products.description, products.price, products.currency_id, products.category_id, products.status, products.created_at, products.updated_at,
  currencies.id, currencies.code, currencies.name, currencies.symbol, currencies.decimals
FROM
  products
  JOIN currencies ON products.currency_id = currencies.id
ORDER BY
  created_at DESC
LIMIT
  $1
OFFSET
  $2
`

type ListProductsParams struct {
	Limit  int32
	Offset int32
}

type ListProductsRow struct {
	Product  Product
	Currency Currency
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.Product.ProductID,
			&i.Product.Sku,
			&i.Product.Name,
			&i.Product.Description,
			&i.Product.Price,
			&i.Product.CurrencyID,
			&i.Product.CategoryID,
			&i.Product.Status,
			&i.Product.CreatedAt,
			&i.Product.UpdatedAt,
			&i.Currency.ID,
			&i.Currency.Code,
			&i.Currency.Name,
			&i.Currency.Symbol,
			&i.Currency.Decimals,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
WITH
  updated AS (
    UPDATE products
    SET
      sku = $1,
      name = $2,
      description = $3,
      price = $4,
      currency_id = $5,
      category_id = $6,
      status = $7,
      updated_at = NOW()
    WHERE
      products.product_id = $8
    RETURNING
      product_id, sku, name, description, price, currency_id, category_id, status, created_at, updated_at
  )
SELECT
  products.product_id, products.sku, products.name, products.description, products.price, products.currency_id, products.category_id, products.status, products.created_at, products.updated_at,
  currencies.id, currencies.code, currencies.name, currencies.symbol, currencies.decimals
FROM
  updated
  JOIN products ON products.product_id = updated.product_id
  LEFT JOIN currencies ON products.currency_id = currencies.id
`

type UpdateProductParams struct {
	Sku         string
	Name        string
	Description sql.NullString
	Price       int64
	CurrencyID  uuid.UUID
	CategoryID  uuid.NullUUID
	Status      string
	ProductID   uuid.UUID
}

type UpdateProductRow struct {
	Product  Product
	Currency Currency
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.Sku,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.CurrencyID,
		arg.CategoryID,
		arg.Status,
		arg.ProductID,
	)
	var i UpdateProductRow
	err := row.Scan(
		&i.Product.ProductID,
		&i.Product.Sku,
		&i.Product.Name,
		&i.Product.Description,
		&i.Product.Price,
		&i.Product.CurrencyID,
		&i.Product.CategoryID,
		&i.Product.Status,
		&i.Product.CreatedAt,
		&i.Product.UpdatedAt,
		&i.Currency.ID,
		&i.Currency.Code,
		&i.Currency.Name,
		&i.Currency.Symbol,
		&i.Currency.Decimals,
	)
	return i, err
}
