// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (CreateProductRow, error)
	CreateStockRecord(ctx context.Context, arg CreateStockRecordParams) (StockRecord, error)
	DeleteProduct(ctx context.Context, productID uuid.UUID) (Product, error)
	GetProductByID(ctx context.Context, productID uuid.UUID) (GetProductByIDRow, error)
	GetProductBySKU(ctx context.Context, sku string) (GetProductBySKURow, error)
	GetStockRecordByProductID(ctx context.Context, productID uuid.UUID) (StockRecord, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (UpdateProductRow, error)
	UpdateStockRecord(ctx context.Context, arg UpdateStockRecordParams) (StockRecord, error)
}

var _ Querier = (*Queries)(nil)
