// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createStockRecord = `-- name: CreateStockRecord :one
INSERT INTO
  stock_records (product_id, quantity, reserved)
VALUES
  (
    $1,
    $2,
    $3
  )
RETURNING
  stock_record_id, product_id, quantity, reserved, available, created_at, updated_at
`

type CreateStockRecordParams struct {
	ProductID uuid.UUID
	Quantity  int32
	Reserved  int32
}

func (q *Queries) CreateStockRecord(ctx context.Context, arg CreateStockRecordParams) (StockRecord, error) {
	row := q.db.QueryRowContext(ctx, createStockRecord, arg.ProductID, arg.Quantity, arg.Reserved)
	var i StockRecord
	err := row.Scan(
		&i.StockRecordID,
		&i.ProductID,
		&i.Quantity,
		&i.Reserved,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStockRecordByProductID = `-- name: GetStockRecordByProductID :one
SELECT
  stock_record_id, product_id, quantity, reserved, available, created_at, updated_at
FROM
  stock_records
WHERE
  product_id = $1
`

func (q *Queries) GetStockRecordByProductID(ctx context.Context, productID uuid.UUID) (StockRecord, error) {
	row := q.db.QueryRowContext(ctx, getStockRecordByProductID, productID)
	var i StockRecord
	err := row.Scan(
		&i.StockRecordID,
		&i.ProductID,
		&i.Quantity,
		&i.Reserved,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStockRecord = `-- name: UpdateStockRecord :one
UPDATE stock_records
SET
  quantity = $1,
  reserved = $2,
  updated_at = NOW()
WHERE
  stock_record_id = $3
RETURNING
  stock_record_id, product_id, quantity, reserved, available, created_at, updated_at
`

type UpdateStockRecordParams struct {
	Quantity      int32
	Reserved      int32
	StockRecordID uuid.UUID
}

func (q *Queries) UpdateStockRecord(ctx context.Context, arg UpdateStockRecordParams) (StockRecord, error) {
	row := q.db.QueryRowContext(ctx, updateStockRecord, arg.Quantity, arg.Reserved, arg.StockRecordID)
	var i StockRecord
	err := row.Scan(
		&i.StockRecordID,
		&i.ProductID,
		&i.Quantity,
		&i.Reserved,
		&i.Available,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
