// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type User struct {
	UserID       string
	Email        string
	PasswordHash string
	DisplayName  sql.NullString
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
