// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Session struct {
	SessionID uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
	RevokedAt sql.NullTime
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	UserID       uuid.UUID
	Email        string
	PasswordHash string
	DisplayName  sql.NullString
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
