// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO
  sessions (user_id, token_hash, expires_at)
VALUES
  ($1, $2, $3)
RETURNING
  session_id,
  user_id,
  token_hash,
  expires_at,
  revoked_at,
  created_at,
  updated_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID
	TokenHash string
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT
  session_id,
  user_id,
  token_hash,
  expires_at,
  revoked_at,
  created_at,
  updated_at
FROM
  sessions
WHERE
  session_id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, sessionID uuid.UUID) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, sessionID)
	var i Session
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
