// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package dto

import (
	"context"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for CartStatus.
const (
	Active     CartStatus = "active"
	CheckedOut CartStatus = "checked_out"
	Expired    CartStatus = "expired"
)

// AddCartItemRequest defines model for AddCartItemRequest.
type AddCartItemRequest struct {
	Quantity int    `json:"quantity" validate:"required,min=1"`
	Sku      string `json:"sku" validate:"required"`
}

// Cart defines model for Cart.
type Cart struct {
	CartId      string     `json:"cartId"`
	Currency    string     `json:"currency"`
	Items       []CartItem `json:"items"`
	Status      CartStatus `json:"status"`
	TotalAmount int        `json:"totalAmount"`
	UserId      string     `json:"userId"`
}

// CartStatus defines model for Cart.Status.
type CartStatus string

// CartItem defines model for CartItem.
type CartItem struct {
	Currency  *string `json:"currency,omitempty"`
	LineTotal int     `json:"lineTotal"`
	Name      *string `json:"name,omitempty"`
	Quantity  int     `json:"quantity"`
	Sku       string  `json:"sku"`
	UnitPrice int     `json:"unitPrice"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code          string  `json:"code"`
	CorrelationId *string `json:"correlationId,omitempty"`
	Message       string  `json:"message"`
}

// UpdateCartItemRequest defines model for UpdateCartItemRequest.
type UpdateCartItemRequest struct {
	Quantity int `json:"quantity" validate:"required,min=1"`
}

// Sku defines model for Sku.
type Sku = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// AddCartItemJSONRequestBody defines body for AddCartItem for application/json ContentType.
type AddCartItemJSONRequestBody = AddCartItemRequest

// UpdateCartItemJSONRequestBody defines body for UpdateCartItem for application/json ContentType.
type UpdateCartItemJSONRequestBody = UpdateCartItemRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get active cart
	// (GET /v1/cart)
	GetActiveCart(w http.ResponseWriter, r *http.Request)
	// Add item to cart
	// (POST /v1/cart/items)
	AddCartItem(w http.ResponseWriter, r *http.Request)
	// Remove item from cart
	// (DELETE /v1/cart/items/{sku})
	RemoveCartItem(w http.ResponseWriter, r *http.Request, sku Sku)
	// Update cart item quantity
	// (PATCH /v1/cart/items/{sku})
	UpdateCartItem(w http.ResponseWriter, r *http.Request, sku Sku)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get active cart
// (GET /v1/cart)
func (_ Unimplemented) GetActiveCart(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add item to cart
// (POST /v1/cart/items)
func (_ Unimplemented) AddCartItem(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove item from cart
// (DELETE /v1/cart/items/{sku})
func (_ Unimplemented) RemoveCartItem(w http.ResponseWriter, r *http.Request, sku Sku) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update cart item quantity
// (PATCH /v1/cart/items/{sku})
func (_ Unimplemented) UpdateCartItem(w http.ResponseWriter, r *http.Request, sku Sku) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetActiveCart operation middleware
func (siw *ServerInterfaceWrapper) GetActiveCart(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetActiveCart(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddCartItem operation middleware
func (siw *ServerInterfaceWrapper) AddCartItem(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddCartItem(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RemoveCartItem operation middleware
func (siw *ServerInterfaceWrapper) RemoveCartItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sku" -------------
	var sku Sku

	err = runtime.BindStyledParameterWithOptions("simple", "sku", chi.URLParam(r, "sku"), &sku, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sku", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RemoveCartItem(w, r, sku)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCartItem operation middleware
func (siw *ServerInterfaceWrapper) UpdateCartItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sku" -------------
	var sku Sku

	err = runtime.BindStyledParameterWithOptions("simple", "sku", chi.URLParam(r, "sku"), &sku, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sku", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCartItem(w, r, sku)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/cart", wrapper.GetActiveCart)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/cart/items", wrapper.AddCartItem)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/cart/items/{sku}", wrapper.RemoveCartItem)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/cart/items/{sku}", wrapper.UpdateCartItem)
	})

	return r
}
