// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type OrderSagaStage string

const (
	OrderSagaStageNotStarted OrderSagaStage = "not_started"
	OrderSagaStageRequested  OrderSagaStage = "requested"
	OrderSagaStageSucceeded  OrderSagaStage = "succeeded"
	OrderSagaStageFailed     OrderSagaStage = "failed"
)

func (e *OrderSagaStage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderSagaStage(s)
	case string:
		*e = OrderSagaStage(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderSagaStage: %T", src)
	}
	return nil
}

type NullOrderSagaStage struct {
	OrderSagaStage OrderSagaStage
	Valid          bool // Valid is true if OrderSagaStage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderSagaStage) Scan(value interface{}) error {
	if value == nil {
		ns.OrderSagaStage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderSagaStage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderSagaStage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderSagaStage), nil
}

type OrderStatus string

const (
	OrderStatusPending         OrderStatus = "pending"
	OrderStatusAwaitingStock   OrderStatus = "awaiting_stock"
	OrderStatusAwaitingPayment OrderStatus = "awaiting_payment"
	OrderStatusConfirmed       OrderStatus = "confirmed"
	OrderStatusCancelled       OrderStatus = "cancelled"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type Order struct {
	OrderID     uuid.UUID
	UserID      uuid.UUID
	Status      OrderStatus
	Currency    string
	TotalAmount int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type OrderCheckoutIdempotency struct {
	OrderCheckoutIdempotencyID uuid.UUID
	OrderID                    uuid.UUID
	UserID                     uuid.UUID
	IdempotencyKey             string
	PayloadFingerprint         string
	CreatedAt                  time.Time
}

type OrderItem struct {
	OrderItemID uuid.UUID
	OrderID     uuid.UUID
	ProductID   uuid.UUID
	Sku         string
	Name        string
	Quantity    int32
	UnitPrice   int64
	LineTotal   int64
	Currency    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type OrderSagaState struct {
	OrderID       uuid.UUID
	StockStage    OrderSagaStage
	PaymentStage  OrderSagaStage
	LastErrorCode sql.NullString
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type OrderStatusHistory struct {
	OrderStatusHistoryID uuid.UUID
	OrderID              uuid.UUID
	FromStatus           sql.NullString
	ToStatus             string
	ReasonCode           sql.NullString
	CreatedAt            time.Time
}

type OutboxRecord struct {
	ID            uuid.UUID
	EventID       uuid.UUID
	EventName     string
	AggregateType string
	AggregateID   string
	Topic         string
	Key           []byte
	Payload       []byte
	Headers       json.RawMessage
	Attempt       int32
	Status        interface{}
	LastError     sql.NullString
	NextAttemptAt time.Time
	LockedAt      sql.NullTime
	LockedBy      sql.NullString
	PublishedAt   sql.NullTime
	MaxAttempts   int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
