// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const appendOrderStatusHistory = `-- name: AppendOrderStatusHistory :one
INSERT INTO
  order_status_history (order_id, from_status, to_status, reason_code)
VALUES
  (
    $1,
    $2,
    $3,
    $4
  )
RETURNING
  order_status_history_id, order_id, from_status, to_status, reason_code, created_at
`

type AppendOrderStatusHistoryParams struct {
	OrderID    uuid.UUID
	FromStatus sql.NullString
	ToStatus   string
	ReasonCode sql.NullString
}

func (q *Queries) AppendOrderStatusHistory(ctx context.Context, arg AppendOrderStatusHistoryParams) (OrderStatusHistory, error) {
	row := q.db.QueryRowContext(ctx, appendOrderStatusHistory,
		arg.OrderID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ReasonCode,
	)
	var i OrderStatusHistory
	err := row.Scan(
		&i.OrderStatusHistoryID,
		&i.OrderID,
		&i.FromStatus,
		&i.ToStatus,
		&i.ReasonCode,
		&i.CreatedAt,
	)
	return i, err
}

const clearOrderSagaLastErrorCode = `-- name: ClearOrderSagaLastErrorCode :one
UPDATE order_saga_state
SET
  last_error_code = NULL,
  updated_at = NOW()
WHERE
  order_id = $1
RETURNING
  order_id, stock_stage, payment_stage, last_error_code, created_at, updated_at
`

func (q *Queries) ClearOrderSagaLastErrorCode(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error) {
	row := q.db.QueryRowContext(ctx, clearOrderSagaLastErrorCode, orderID)
	var i OrderSagaState
	err := row.Scan(
		&i.OrderID,
		&i.StockStage,
		&i.PaymentStage,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO
  orders (order_id, user_id, status, currency, total_amount)
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5
  )
RETURNING
  order_id, user_id, status, currency, total_amount, created_at, updated_at
`

type CreateOrderParams struct {
	OrderID     uuid.UUID
	UserID      uuid.UUID
	Status      OrderStatus
	Currency    string
	TotalAmount int64
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.OrderID,
		arg.UserID,
		arg.Status,
		arg.Currency,
		arg.TotalAmount,
	)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderCheckoutIdempotency = `-- name: CreateOrderCheckoutIdempotency :exec
INSERT INTO
  order_checkout_idempotency (order_id, user_id, idempotency_key)
VALUES
  (
    $1,
    $2,
    $3
  )
`

type CreateOrderCheckoutIdempotencyParams struct {
	OrderID        uuid.UUID
	UserID         uuid.UUID
	IdempotencyKey string
}

func (q *Queries) CreateOrderCheckoutIdempotency(ctx context.Context, arg CreateOrderCheckoutIdempotencyParams) error {
	_, err := q.db.ExecContext(ctx, createOrderCheckoutIdempotency, arg.OrderID, arg.UserID, arg.IdempotencyKey)
	return err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO
  order_items (
    order_id,
    product_id,
    sku,
    name,
    quantity,
    unit_price,
    line_total,
    currency
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
  )
RETURNING
  order_item_id, order_id, product_id, sku, name, quantity, unit_price, line_total, currency, created_at, updated_at
`

type CreateOrderItemParams struct {
	OrderID   uuid.UUID
	ProductID uuid.UUID
	Sku       string
	Name      string
	Quantity  int32
	UnitPrice int64
	LineTotal int64
	Currency  string
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Sku,
		arg.Name,
		arg.Quantity,
		arg.UnitPrice,
		arg.LineTotal,
		arg.Currency,
	)
	var i OrderItem
	err := row.Scan(
		&i.OrderItemID,
		&i.OrderID,
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.Quantity,
		&i.UnitPrice,
		&i.LineTotal,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderSagaState = `-- name: CreateOrderSagaState :one
INSERT INTO
  order_saga_state (order_id, stock_stage, payment_stage, last_error_code)
VALUES
  (
    $1,
    $2,
    $3,
    $4
  )
RETURNING
  order_id, stock_stage, payment_stage, last_error_code, created_at, updated_at
`

type CreateOrderSagaStateParams struct {
	OrderID       uuid.UUID
	StockStage    OrderSagaStage
	PaymentStage  OrderSagaStage
	LastErrorCode sql.NullString
}

func (q *Queries) CreateOrderSagaState(ctx context.Context, arg CreateOrderSagaStateParams) (OrderSagaState, error) {
	row := q.db.QueryRowContext(ctx, createOrderSagaState,
		arg.OrderID,
		arg.StockStage,
		arg.PaymentStage,
		arg.LastErrorCode,
	)
	var i OrderSagaState
	err := row.Scan(
		&i.OrderID,
		&i.StockStage,
		&i.PaymentStage,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT
  order_id, user_id, status, currency, total_amount, created_at, updated_at
FROM
  orders
WHERE
  order_id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, orderID uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, orderID)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByUserIDAndIdempotencyKey = `-- name: GetOrderByUserIDAndIdempotencyKey :one
SELECT
  o.order_id, o.user_id, o.status, o.currency, o.total_amount, o.created_at, o.updated_at
FROM
  order_checkout_idempotency i
  INNER JOIN orders o ON o.order_id = i.order_id
WHERE
  i.user_id = $1
  AND i.idempotency_key = $2
`

type GetOrderByUserIDAndIdempotencyKeyParams struct {
	UserID         uuid.UUID
	IdempotencyKey string
}

func (q *Queries) GetOrderByUserIDAndIdempotencyKey(ctx context.Context, arg GetOrderByUserIDAndIdempotencyKeyParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByUserIDAndIdempotencyKey, arg.UserID, arg.IdempotencyKey)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderSagaStateByOrderID = `-- name: GetOrderSagaStateByOrderID :one
SELECT
  order_id, stock_stage, payment_stage, last_error_code, created_at, updated_at
FROM
  order_saga_state
WHERE
  order_id = $1
`

func (q *Queries) GetOrderSagaStateByOrderID(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error) {
	row := q.db.QueryRowContext(ctx, getOrderSagaStateByOrderID, orderID)
	var i OrderSagaState
	err := row.Scan(
		&i.OrderID,
		&i.StockStage,
		&i.PaymentStage,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT
  order_item_id, order_id, product_id, sku, name, quantity, unit_price, line_total, currency, created_at, updated_at
FROM
  order_items
WHERE
  order_id = $1
ORDER BY
  created_at ASC
`

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.OrderItemID,
			&i.OrderID,
			&i.ProductID,
			&i.Sku,
			&i.Name,
			&i.Quantity,
			&i.UnitPrice,
			&i.LineTotal,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderSagaPaymentFailed = `-- name: MarkOrderSagaPaymentFailed :one
UPDATE order_saga_state
SET
  payment_stage = 'failed',
  updated_at = NOW()
WHERE
  order_id = $1
  AND payment_stage IN ('requested', 'failed')
RETURNING
  order_id, stock_stage, payment_stage, last_error_code, created_at, updated_at
`

func (q *Queries) MarkOrderSagaPaymentFailed(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error) {
	row := q.db.QueryRowContext(ctx, markOrderSagaPaymentFailed, orderID)
	var i OrderSagaState
	err := row.Scan(
		&i.OrderID,
		&i.StockStage,
		&i.PaymentStage,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOrderSagaPaymentRequested = `-- name: MarkOrderSagaPaymentRequested :one
UPDATE order_saga_state
SET
  payment_stage = 'requested',
  updated_at = NOW()
WHERE
  order_id = $1
  AND payment_stage IN ('not_started', 'requested')
RETURNING
  order_id, stock_stage, payment_stage, last_error_code, created_at, updated_at
`

func (q *Queries) MarkOrderSagaPaymentRequested(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error) {
	row := q.db.QueryRowContext(ctx, markOrderSagaPaymentRequested, orderID)
	var i OrderSagaState
	err := row.Scan(
		&i.OrderID,
		&i.StockStage,
		&i.PaymentStage,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOrderSagaPaymentSucceeded = `-- name: MarkOrderSagaPaymentSucceeded :one
UPDATE order_saga_state
SET
  payment_stage = 'succeeded',
  updated_at = NOW()
WHERE
  order_id = $1
  AND payment_stage IN ('requested', 'succeeded')
RETURNING
  order_id, stock_stage, payment_stage, last_error_code, created_at, updated_at
`

func (q *Queries) MarkOrderSagaPaymentSucceeded(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error) {
	row := q.db.QueryRowContext(ctx, markOrderSagaPaymentSucceeded, orderID)
	var i OrderSagaState
	err := row.Scan(
		&i.OrderID,
		&i.StockStage,
		&i.PaymentStage,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOrderSagaStockFailed = `-- name: MarkOrderSagaStockFailed :one
UPDATE order_saga_state
SET
  stock_stage = 'failed',
  updated_at = NOW()
WHERE
  order_id = $1
  AND stock_stage IN ('requested', 'failed')
RETURNING
  order_id, stock_stage, payment_stage, last_error_code, created_at, updated_at
`

func (q *Queries) MarkOrderSagaStockFailed(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error) {
	row := q.db.QueryRowContext(ctx, markOrderSagaStockFailed, orderID)
	var i OrderSagaState
	err := row.Scan(
		&i.OrderID,
		&i.StockStage,
		&i.PaymentStage,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOrderSagaStockRequested = `-- name: MarkOrderSagaStockRequested :one
UPDATE order_saga_state
SET
  stock_stage = 'requested',
  updated_at = NOW()
WHERE
  order_id = $1
  AND stock_stage IN ('not_started', 'requested')
RETURNING
  order_id, stock_stage, payment_stage, last_error_code, created_at, updated_at
`

func (q *Queries) MarkOrderSagaStockRequested(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error) {
	row := q.db.QueryRowContext(ctx, markOrderSagaStockRequested, orderID)
	var i OrderSagaState
	err := row.Scan(
		&i.OrderID,
		&i.StockStage,
		&i.PaymentStage,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOrderSagaStockSucceeded = `-- name: MarkOrderSagaStockSucceeded :one
UPDATE order_saga_state
SET
  stock_stage = 'succeeded',
  updated_at = NOW()
WHERE
  order_id = $1
  AND stock_stage IN ('requested', 'succeeded')
RETURNING
  order_id, stock_stage, payment_stage, last_error_code, created_at, updated_at
`

func (q *Queries) MarkOrderSagaStockSucceeded(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error) {
	row := q.db.QueryRowContext(ctx, markOrderSagaStockSucceeded, orderID)
	var i OrderSagaState
	err := row.Scan(
		&i.OrderID,
		&i.StockStage,
		&i.PaymentStage,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setOrderSagaLastErrorCode = `-- name: SetOrderSagaLastErrorCode :one
UPDATE order_saga_state
SET
  last_error_code = $1,
  updated_at = NOW()
WHERE
  order_id = $2
RETURNING
  order_id, stock_stage, payment_stage, last_error_code, created_at, updated_at
`

type SetOrderSagaLastErrorCodeParams struct {
	LastErrorCode sql.NullString
	OrderID       uuid.UUID
}

func (q *Queries) SetOrderSagaLastErrorCode(ctx context.Context, arg SetOrderSagaLastErrorCodeParams) (OrderSagaState, error) {
	row := q.db.QueryRowContext(ctx, setOrderSagaLastErrorCode, arg.LastErrorCode, arg.OrderID)
	var i OrderSagaState
	err := row.Scan(
		&i.OrderID,
		&i.StockStage,
		&i.PaymentStage,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transitionOrderStatus = `-- name: TransitionOrderStatus :one
UPDATE orders
SET
  status = $1,
  updated_at = NOW()
WHERE
  order_id = $2
  AND status = $3
RETURNING
  order_id, user_id, status, currency, total_amount, created_at, updated_at
`

type TransitionOrderStatusParams struct {
	ToStatus   OrderStatus
	OrderID    uuid.UUID
	FromStatus OrderStatus
}

func (q *Queries) TransitionOrderStatus(ctx context.Context, arg TransitionOrderStatusParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, transitionOrderStatus, arg.ToStatus, arg.OrderID, arg.FromStatus)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
