// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const appendOrderStatusHistory = `-- name: AppendOrderStatusHistory :one
INSERT INTO
  order_status_history (order_id, from_status, to_status, reason_code)
VALUES
  (
    $1,
    $2,
    $3,
    $4
  )
RETURNING
  order_status_history_id, order_id, from_status, to_status, reason_code, created_at
`

type AppendOrderStatusHistoryParams struct {
	OrderID    uuid.UUID
	FromStatus sql.NullString
	ToStatus   string
	ReasonCode sql.NullString
}

func (q *Queries) AppendOrderStatusHistory(ctx context.Context, arg AppendOrderStatusHistoryParams) (OrderStatusHistory, error) {
	row := q.db.QueryRowContext(ctx, appendOrderStatusHistory,
		arg.OrderID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ReasonCode,
	)
	var i OrderStatusHistory
	err := row.Scan(
		&i.OrderStatusHistoryID,
		&i.OrderID,
		&i.FromStatus,
		&i.ToStatus,
		&i.ReasonCode,
		&i.CreatedAt,
	)
	return i, err
}

const appendOutboxRecord = `-- name: AppendOutboxRecord :one
INSERT INTO
  outbox_records (
    event_id,
    event_name,
    aggregate_type,
    aggregate_id,
    topic,
    key,
    payload,
    headers,
    status
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
  )
RETURNING
  id, event_id, event_name, aggregate_type, aggregate_id, topic, key, payload, headers, attempt, status, last_error, next_attempt_at, locked_at, locked_by, published_at, max_attempts, created_at, updated_at
`

type AppendOutboxRecordParams struct {
	EventID       uuid.UUID
	EventName     string
	AggregateType string
	AggregateID   string
	Topic         string
	Key           []byte
	Payload       []byte
	Headers       json.RawMessage
	Status        interface{}
}

func (q *Queries) AppendOutboxRecord(ctx context.Context, arg AppendOutboxRecordParams) (OutboxRecord, error) {
	row := q.db.QueryRowContext(ctx, appendOutboxRecord,
		arg.EventID,
		arg.EventName,
		arg.AggregateType,
		arg.AggregateID,
		arg.Topic,
		arg.Key,
		arg.Payload,
		arg.Headers,
		arg.Status,
	)
	var i OutboxRecord
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventName,
		&i.AggregateType,
		&i.AggregateID,
		&i.Topic,
		&i.Key,
		&i.Payload,
		&i.Headers,
		&i.Attempt,
		&i.Status,
		&i.LastError,
		&i.NextAttemptAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.PublishedAt,
		&i.MaxAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimPendingOutboxRecords = `-- name: ClaimPendingOutboxRecords :many
WITH candidates AS (
  SELECT
    o.id
  FROM
    outbox_records AS o
  WHERE
    o.status = 'pending'
    AND o.next_attempt_at <= $3
  ORDER BY
    o.next_attempt_at,
    o.created_at,
    o.id
  LIMIT
    $4
  FOR UPDATE
    SKIP LOCKED
)
UPDATE outbox_records AS o
SET
  status = 'in_progress',
  locked_at = $1,
  locked_by = $2,
  updated_at = $1
FROM
  candidates
WHERE
  o.id = candidates.id
RETURNING
  o.id, o.event_id, o.event_name, o.aggregate_type, o.aggregate_id, o.topic, o.key, o.payload, o.headers, o.attempt, o.status, o.last_error, o.next_attempt_at, o.locked_at, o.locked_by, o.published_at, o.max_attempts, o.created_at, o.updated_at
`

type ClaimPendingOutboxRecordsParams struct {
	ClaimedAt  sql.NullTime
	LockedBy   sql.NullString
	Before     time.Time
	LimitCount int32
}

func (q *Queries) ClaimPendingOutboxRecords(ctx context.Context, arg ClaimPendingOutboxRecordsParams) ([]OutboxRecord, error) {
	rows, err := q.db.QueryContext(ctx, claimPendingOutboxRecords,
		arg.ClaimedAt,
		arg.LockedBy,
		arg.Before,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxRecord
	for rows.Next() {
		var i OutboxRecord
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventName,
			&i.AggregateType,
			&i.AggregateID,
			&i.Topic,
			&i.Key,
			&i.Payload,
			&i.Headers,
			&i.Attempt,
			&i.Status,
			&i.LastError,
			&i.NextAttemptAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.PublishedAt,
			&i.MaxAttempts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimStaleInProgressOutboxRecords = `-- name: ClaimStaleInProgressOutboxRecords :many
WITH candidates AS (
  SELECT
    o.id
  FROM
    outbox_records AS o
  WHERE
    o.status = 'in_progress'
    AND o.locked_at <= $3
  ORDER BY
    o.locked_at,
    o.created_at,
    o.id
  LIMIT
    $4
  FOR UPDATE
    SKIP LOCKED
)
UPDATE outbox_records AS o
SET
  locked_at = $1,
  locked_by = $2,
  updated_at = $1
FROM
  candidates
WHERE
  o.id = candidates.id
RETURNING
  o.id, o.event_id, o.event_name, o.aggregate_type, o.aggregate_id, o.topic, o.key, o.payload, o.headers, o.attempt, o.status, o.last_error, o.next_attempt_at, o.locked_at, o.locked_by, o.published_at, o.max_attempts, o.created_at, o.updated_at
`

type ClaimStaleInProgressOutboxRecordsParams struct {
	ClaimedAt   sql.NullTime
	LockedBy    sql.NullString
	StaleBefore sql.NullTime
	LimitCount  int32
}

func (q *Queries) ClaimStaleInProgressOutboxRecords(ctx context.Context, arg ClaimStaleInProgressOutboxRecordsParams) ([]OutboxRecord, error) {
	rows, err := q.db.QueryContext(ctx, claimStaleInProgressOutboxRecords,
		arg.ClaimedAt,
		arg.LockedBy,
		arg.StaleBefore,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxRecord
	for rows.Next() {
		var i OutboxRecord
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventName,
			&i.AggregateType,
			&i.AggregateID,
			&i.Topic,
			&i.Key,
			&i.Payload,
			&i.Headers,
			&i.Attempt,
			&i.Status,
			&i.LastError,
			&i.NextAttemptAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.PublishedAt,
			&i.MaxAttempts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearOrderSagaLastErrorCode = `-- name: ClearOrderSagaLastErrorCode :one
UPDATE order_saga_state
SET
  last_error_code = NULL,
  updated_at = NOW()
WHERE
  order_id = $1
RETURNING
  order_id, stock_stage, payment_stage, last_error_code, created_at, updated_at
`

func (q *Queries) ClearOrderSagaLastErrorCode(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error) {
	row := q.db.QueryRowContext(ctx, clearOrderSagaLastErrorCode, orderID)
	var i OrderSagaState
	err := row.Scan(
		&i.OrderID,
		&i.StockStage,
		&i.PaymentStage,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO
  orders (order_id, user_id, status, currency, total_amount)
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5
  )
RETURNING
  order_id, user_id, status, currency, total_amount, created_at, updated_at
`

type CreateOrderParams struct {
	OrderID     uuid.UUID
	UserID      uuid.UUID
	Status      OrderStatus
	Currency    string
	TotalAmount int64
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.OrderID,
		arg.UserID,
		arg.Status,
		arg.Currency,
		arg.TotalAmount,
	)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderCheckoutIdempotency = `-- name: CreateOrderCheckoutIdempotency :exec
INSERT INTO
  order_checkout_idempotency (order_id, user_id, idempotency_key, payload_fingerprint)
VALUES
  (
    $1,
    $2,
    $3,
    $4
  )
`

type CreateOrderCheckoutIdempotencyParams struct {
	OrderID            uuid.UUID
	UserID             uuid.UUID
	IdempotencyKey     string
	PayloadFingerprint string
}

func (q *Queries) CreateOrderCheckoutIdempotency(ctx context.Context, arg CreateOrderCheckoutIdempotencyParams) error {
	_, err := q.db.ExecContext(ctx, createOrderCheckoutIdempotency,
		arg.OrderID,
		arg.UserID,
		arg.IdempotencyKey,
		arg.PayloadFingerprint,
	)
	return err
}

const createConsumerIdempotency = `-- name: CreateConsumerIdempotency :exec
INSERT INTO
  order_consumer_idempotency (event_id, consumer_group_name)
VALUES
  (
    $1,
    $2
  )
`

type CreateConsumerIdempotencyParams struct {
	EventID           uuid.UUID
	ConsumerGroupName string
}

func (q *Queries) CreateConsumerIdempotency(ctx context.Context, arg CreateConsumerIdempotencyParams) error {
	_, err := q.db.ExecContext(ctx, createConsumerIdempotency,
		arg.EventID,
		arg.ConsumerGroupName,
	)
	return err
}

const consumerIdempotencyExists = `-- name: ConsumerIdempotencyExists :one
SELECT
  EXISTS (
    SELECT
      1
    FROM
      order_consumer_idempotency
    WHERE
      event_id = $1
      AND consumer_group_name = $2
  )
`

type ConsumerIdempotencyExistsParams struct {
	EventID           uuid.UUID
	ConsumerGroupName string
}

func (q *Queries) ConsumerIdempotencyExists(ctx context.Context, arg ConsumerIdempotencyExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, consumerIdempotencyExists, arg.EventID, arg.ConsumerGroupName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO
  order_items (
    order_id,
    product_id,
    sku,
    name,
    quantity,
    unit_price,
    line_total,
    currency
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
  )
RETURNING
  order_item_id, order_id, product_id, sku, name, quantity, unit_price, line_total, currency, created_at, updated_at
`

type CreateOrderItemParams struct {
	OrderID   uuid.UUID
	ProductID uuid.UUID
	Sku       string
	Name      string
	Quantity  int32
	UnitPrice int64
	LineTotal int64
	Currency  string
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Sku,
		arg.Name,
		arg.Quantity,
		arg.UnitPrice,
		arg.LineTotal,
		arg.Currency,
	)
	var i OrderItem
	err := row.Scan(
		&i.OrderItemID,
		&i.OrderID,
		&i.ProductID,
		&i.Sku,
		&i.Name,
		&i.Quantity,
		&i.UnitPrice,
		&i.LineTotal,
		&i.Currency,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderSagaState = `-- name: CreateOrderSagaState :one
INSERT INTO
  order_saga_state (order_id, stock_stage, payment_stage, last_error_code)
VALUES
  (
    $1,
    $2,
    $3,
    $4
  )
RETURNING
  order_id, stock_stage, payment_stage, last_error_code, created_at, updated_at
`

type CreateOrderSagaStateParams struct {
	OrderID       uuid.UUID
	StockStage    OrderSagaStage
	PaymentStage  OrderSagaStage
	LastErrorCode sql.NullString
}

func (q *Queries) CreateOrderSagaState(ctx context.Context, arg CreateOrderSagaStateParams) (OrderSagaState, error) {
	row := q.db.QueryRowContext(ctx, createOrderSagaState,
		arg.OrderID,
		arg.StockStage,
		arg.PaymentStage,
		arg.LastErrorCode,
	)
	var i OrderSagaState
	err := row.Scan(
		&i.OrderID,
		&i.StockStage,
		&i.PaymentStage,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCheckoutIdempotencyPayloadFingerprint = `-- name: GetCheckoutIdempotencyPayloadFingerprint :one
SELECT
  payload_fingerprint
FROM
  order_checkout_idempotency
WHERE
  user_id = $1
  AND idempotency_key = $2
`

type GetCheckoutIdempotencyPayloadFingerprintParams struct {
	UserID         uuid.UUID
	IdempotencyKey string
}

func (q *Queries) GetCheckoutIdempotencyPayloadFingerprint(ctx context.Context, arg GetCheckoutIdempotencyPayloadFingerprintParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getCheckoutIdempotencyPayloadFingerprint, arg.UserID, arg.IdempotencyKey)
	var payload_fingerprint string
	err := row.Scan(&payload_fingerprint)
	return payload_fingerprint, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT
  order_id, user_id, status, currency, total_amount, created_at, updated_at
FROM
  orders
WHERE
  order_id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, orderID uuid.UUID) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, orderID)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByUserIDAndIdempotencyKey = `-- name: GetOrderByUserIDAndIdempotencyKey :one
SELECT
  o.order_id, o.user_id, o.status, o.currency, o.total_amount, o.created_at, o.updated_at
FROM
  order_checkout_idempotency i
  INNER JOIN orders o ON o.order_id = i.order_id
WHERE
  i.user_id = $1
  AND i.idempotency_key = $2
`

type GetOrderByUserIDAndIdempotencyKeyParams struct {
	UserID         uuid.UUID
	IdempotencyKey string
}

func (q *Queries) GetOrderByUserIDAndIdempotencyKey(ctx context.Context, arg GetOrderByUserIDAndIdempotencyKeyParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrderByUserIDAndIdempotencyKey, arg.UserID, arg.IdempotencyKey)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderSagaStateByOrderID = `-- name: GetOrderSagaStateByOrderID :one
SELECT
  order_id, stock_stage, payment_stage, last_error_code, created_at, updated_at
FROM
  order_saga_state
WHERE
  order_id = $1
`

func (q *Queries) GetOrderSagaStateByOrderID(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error) {
	row := q.db.QueryRowContext(ctx, getOrderSagaStateByOrderID, orderID)
	var i OrderSagaState
	err := row.Scan(
		&i.OrderID,
		&i.StockStage,
		&i.PaymentStage,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrderItemsByOrderID = `-- name: ListOrderItemsByOrderID :many
SELECT
  order_item_id, order_id, product_id, sku, name, quantity, unit_price, line_total, currency, created_at, updated_at
FROM
  order_items
WHERE
  order_id = $1
ORDER BY
  created_at ASC
`

func (q *Queries) ListOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.OrderItemID,
			&i.OrderID,
			&i.ProductID,
			&i.Sku,
			&i.Name,
			&i.Quantity,
			&i.UnitPrice,
			&i.LineTotal,
			&i.Currency,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOrderSagaPaymentFailed = `-- name: MarkOrderSagaPaymentFailed :one
UPDATE order_saga_state
SET
  payment_stage = 'failed',
  updated_at = NOW()
WHERE
  order_id = $1
  AND stock_stage = 'succeeded'
  AND payment_stage IN ('requested', 'failed')
RETURNING
  order_id, stock_stage, payment_stage, last_error_code, created_at, updated_at
`

func (q *Queries) MarkOrderSagaPaymentFailed(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error) {
	row := q.db.QueryRowContext(ctx, markOrderSagaPaymentFailed, orderID)
	var i OrderSagaState
	err := row.Scan(
		&i.OrderID,
		&i.StockStage,
		&i.PaymentStage,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOrderSagaPaymentRequested = `-- name: MarkOrderSagaPaymentRequested :one
UPDATE order_saga_state
SET
  payment_stage = 'requested',
  updated_at = NOW()
WHERE
  order_id = $1
  AND stock_stage = 'succeeded'
  AND payment_stage IN ('not_started', 'requested')
RETURNING
  order_id, stock_stage, payment_stage, last_error_code, created_at, updated_at
`

func (q *Queries) MarkOrderSagaPaymentRequested(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error) {
	row := q.db.QueryRowContext(ctx, markOrderSagaPaymentRequested, orderID)
	var i OrderSagaState
	err := row.Scan(
		&i.OrderID,
		&i.StockStage,
		&i.PaymentStage,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOrderSagaPaymentSucceeded = `-- name: MarkOrderSagaPaymentSucceeded :one
UPDATE order_saga_state
SET
  payment_stage = 'succeeded',
  updated_at = NOW()
WHERE
  order_id = $1
  AND stock_stage = 'succeeded'
  AND payment_stage IN ('requested', 'succeeded')
RETURNING
  order_id, stock_stage, payment_stage, last_error_code, created_at, updated_at
`

func (q *Queries) MarkOrderSagaPaymentSucceeded(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error) {
	row := q.db.QueryRowContext(ctx, markOrderSagaPaymentSucceeded, orderID)
	var i OrderSagaState
	err := row.Scan(
		&i.OrderID,
		&i.StockStage,
		&i.PaymentStage,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOrderSagaStockFailed = `-- name: MarkOrderSagaStockFailed :one
UPDATE order_saga_state
SET
  stock_stage = 'failed',
  updated_at = NOW()
WHERE
  order_id = $1
  AND stock_stage IN ('requested', 'failed')
RETURNING
  order_id, stock_stage, payment_stage, last_error_code, created_at, updated_at
`

func (q *Queries) MarkOrderSagaStockFailed(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error) {
	row := q.db.QueryRowContext(ctx, markOrderSagaStockFailed, orderID)
	var i OrderSagaState
	err := row.Scan(
		&i.OrderID,
		&i.StockStage,
		&i.PaymentStage,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOrderSagaStockRequested = `-- name: MarkOrderSagaStockRequested :one
UPDATE order_saga_state
SET
  stock_stage = 'requested',
  updated_at = NOW()
WHERE
  order_id = $1
  AND stock_stage IN ('not_started', 'requested')
RETURNING
  order_id, stock_stage, payment_stage, last_error_code, created_at, updated_at
`

func (q *Queries) MarkOrderSagaStockRequested(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error) {
	row := q.db.QueryRowContext(ctx, markOrderSagaStockRequested, orderID)
	var i OrderSagaState
	err := row.Scan(
		&i.OrderID,
		&i.StockStage,
		&i.PaymentStage,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOrderSagaStockSucceeded = `-- name: MarkOrderSagaStockSucceeded :one
UPDATE order_saga_state
SET
  stock_stage = 'succeeded',
  updated_at = NOW()
WHERE
  order_id = $1
  AND stock_stage IN ('requested', 'succeeded')
RETURNING
  order_id, stock_stage, payment_stage, last_error_code, created_at, updated_at
`

func (q *Queries) MarkOrderSagaStockSucceeded(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error) {
	row := q.db.QueryRowContext(ctx, markOrderSagaStockSucceeded, orderID)
	var i OrderSagaState
	err := row.Scan(
		&i.OrderID,
		&i.StockStage,
		&i.PaymentStage,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markOutboxRecordDead = `-- name: MarkOutboxRecordDead :execrows
UPDATE outbox_records
SET
  status = 'dead',
  attempt = $1,
  next_attempt_at = $2,
  last_error = $3,
  locked_at = NULL,
  locked_by = NULL,
  updated_at = $2
WHERE
  id = $4
  AND status = 'in_progress'
  AND locked_by = $5
  AND locked_at = $6
`

type MarkOutboxRecordDeadParams struct {
	Attempt    int32
	UpdatedAt  time.Time
	LastError  sql.NullString
	ID         uuid.UUID
	LockedBy   sql.NullString
	ClaimToken sql.NullTime
}

func (q *Queries) MarkOutboxRecordDead(ctx context.Context, arg MarkOutboxRecordDeadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOutboxRecordDead,
		arg.Attempt,
		arg.UpdatedAt,
		arg.LastError,
		arg.ID,
		arg.LockedBy,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markOutboxRecordPublished = `-- name: MarkOutboxRecordPublished :execrows
UPDATE outbox_records
SET
  status = 'published',
  published_at = $1,
  locked_at = NULL,
  locked_by = NULL,
  updated_at = $1
WHERE
  id = $2
  AND status = 'in_progress'
  AND locked_by = $3
  AND locked_at = $4
`

type MarkOutboxRecordPublishedParams struct {
	PublishedAt sql.NullTime
	ID          uuid.UUID
	LockedBy    sql.NullString
	ClaimToken  sql.NullTime
}

func (q *Queries) MarkOutboxRecordPublished(ctx context.Context, arg MarkOutboxRecordPublishedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOutboxRecordPublished,
		arg.PublishedAt,
		arg.ID,
		arg.LockedBy,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markOutboxRecordRetryableFailure = `-- name: MarkOutboxRecordRetryableFailure :execrows
UPDATE outbox_records
SET
  status = 'pending',
  attempt = $1,
  next_attempt_at = $2,
  last_error = $3,
  locked_at = NULL,
  locked_by = NULL,
  updated_at = $4
WHERE
  id = $5
  AND status = 'in_progress'
  AND locked_by = $6
  AND locked_at = $7
`

type MarkOutboxRecordRetryableFailureParams struct {
	Attempt       int32
	NextAttemptAt time.Time
	LastError     sql.NullString
	UpdatedAt     time.Time
	ID            uuid.UUID
	LockedBy      sql.NullString
	ClaimToken    sql.NullTime
}

func (q *Queries) MarkOutboxRecordRetryableFailure(ctx context.Context, arg MarkOutboxRecordRetryableFailureParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOutboxRecordRetryableFailure,
		arg.Attempt,
		arg.NextAttemptAt,
		arg.LastError,
		arg.UpdatedAt,
		arg.ID,
		arg.LockedBy,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setOrderSagaLastErrorCode = `-- name: SetOrderSagaLastErrorCode :one
UPDATE order_saga_state
SET
  last_error_code = $1,
  updated_at = NOW()
WHERE
  order_id = $2
RETURNING
  order_id, stock_stage, payment_stage, last_error_code, created_at, updated_at
`

type SetOrderSagaLastErrorCodeParams struct {
	LastErrorCode sql.NullString
	OrderID       uuid.UUID
}

func (q *Queries) SetOrderSagaLastErrorCode(ctx context.Context, arg SetOrderSagaLastErrorCodeParams) (OrderSagaState, error) {
	row := q.db.QueryRowContext(ctx, setOrderSagaLastErrorCode, arg.LastErrorCode, arg.OrderID)
	var i OrderSagaState
	err := row.Scan(
		&i.OrderID,
		&i.StockStage,
		&i.PaymentStage,
		&i.LastErrorCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const transitionOrderStatus = `-- name: TransitionOrderStatus :one
UPDATE orders
SET
  status = $1,
  updated_at = NOW()
WHERE
  order_id = $2
  AND status = $3
RETURNING
  order_id, user_id, status, currency, total_amount, created_at, updated_at
`

type TransitionOrderStatusParams struct {
	ToStatus   OrderStatus
	OrderID    uuid.UUID
	FromStatus OrderStatus
}

func (q *Queries) TransitionOrderStatus(ctx context.Context, arg TransitionOrderStatusParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, transitionOrderStatus, arg.ToStatus, arg.OrderID, arg.FromStatus)
	var i Order
	err := row.Scan(
		&i.OrderID,
		&i.UserID,
		&i.Status,
		&i.Currency,
		&i.TotalAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
