// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AppendOrderStatusHistory(ctx context.Context, arg AppendOrderStatusHistoryParams) (OrderStatusHistory, error)
	AppendOutboxRecord(ctx context.Context, arg AppendOutboxRecordParams) (OutboxRecord, error)
	ClaimPendingOutboxRecords(ctx context.Context, arg ClaimPendingOutboxRecordsParams) ([]OutboxRecord, error)
	ClaimStaleInProgressOutboxRecords(ctx context.Context, arg ClaimStaleInProgressOutboxRecordsParams) ([]OutboxRecord, error)
	ClearOrderSagaLastErrorCode(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderCheckoutIdempotency(ctx context.Context, arg CreateOrderCheckoutIdempotencyParams) error
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateOrderSagaState(ctx context.Context, arg CreateOrderSagaStateParams) (OrderSagaState, error)
	GetOrderByID(ctx context.Context, orderID uuid.UUID) (Order, error)
	GetOrderByUserIDAndIdempotencyKey(ctx context.Context, arg GetOrderByUserIDAndIdempotencyKeyParams) (Order, error)
	GetOrderSagaStateByOrderID(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error)
	ListOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]OrderItem, error)
	MarkOrderSagaPaymentFailed(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error)
	MarkOrderSagaPaymentRequested(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error)
	MarkOrderSagaPaymentSucceeded(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error)
	MarkOrderSagaStockFailed(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error)
	MarkOrderSagaStockRequested(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error)
	MarkOrderSagaStockSucceeded(ctx context.Context, orderID uuid.UUID) (OrderSagaState, error)
	MarkOutboxRecordDead(ctx context.Context, arg MarkOutboxRecordDeadParams) (int64, error)
	MarkOutboxRecordPublished(ctx context.Context, arg MarkOutboxRecordPublishedParams) (int64, error)
	MarkOutboxRecordRetryableFailure(ctx context.Context, arg MarkOutboxRecordRetryableFailureParams) (int64, error)
	SetOrderSagaLastErrorCode(ctx context.Context, arg SetOrderSagaLastErrorCodeParams) (OrderSagaState, error)
	TransitionOrderStatus(ctx context.Context, arg TransitionOrderStatusParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
