// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package outboundmocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/shrtyk/e-commerce-platform/internal/product-svc/internal/core/domain"
	"github.com/shrtyk/e-commerce-platform/internal/product-svc/internal/core/ports/outbound"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher {
	mock := &MockEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

type MockEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher) EXPECT() *MockEventPublisher_Expecter {
	return &MockEventPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockEventPublisher
func (_mock *MockEventPublisher) Publish(ctx context.Context, event domain.DomainEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.DomainEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockEventPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.DomainEvent
func (_e *MockEventPublisher_Expecter) Publish(ctx interface{}, event interface{}) *MockEventPublisher_Publish_Call {
	return &MockEventPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, event)}
}

func (_c *MockEventPublisher_Publish_Call) Run(run func(ctx context.Context, event domain.DomainEvent)) *MockEventPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.DomainEvent
		if args[1] != nil {
			arg1 = args[1].(domain.DomainEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventPublisher_Publish_Call) Return(err error) *MockEventPublisher_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventPublisher_Publish_Call) RunAndReturn(run func(ctx context.Context, event domain.DomainEvent) error) *MockEventPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

type MockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepository) EXPECT() *MockProductRepository_Expecter {
	return &MockProductRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) Create(ctx context.Context, product domain.Product) (domain.Product, error) {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Product) (domain.Product, error)); ok {
		return returnFunc(ctx, product)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Product) domain.Product); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Get(0).(domain.Product)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Product) error); ok {
		r1 = returnFunc(ctx, product)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProductRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - product domain.Product
func (_e *MockProductRepository_Expecter) Create(ctx interface{}, product interface{}) *MockProductRepository_Create_Call {
	return &MockProductRepository_Create_Call{Call: _e.mock.On("Create", ctx, product)}
}

func (_c *MockProductRepository_Create_Call) Run(run func(ctx context.Context, product domain.Product)) *MockProductRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Product
		if args[1] != nil {
			arg1 = args[1].(domain.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_Create_Call) Return(product1 domain.Product, err error) *MockProductRepository_Create_Call {
	_c.Call.Return(product1, err)
	return _c
}

func (_c *MockProductRepository_Create_Call) RunAndReturn(run func(ctx context.Context, product domain.Product) (domain.Product, error)) *MockProductRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) Delete(ctx context.Context, productID uuid.UUID) (domain.Product, error) {
	ret := _mock.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 domain.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Product, error)); ok {
		return returnFunc(ctx, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Product); ok {
		r0 = returnFunc(ctx, productID)
	} else {
		r0 = ret.Get(0).(domain.Product)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProductRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
func (_e *MockProductRepository_Expecter) Delete(ctx interface{}, productID interface{}) *MockProductRepository_Delete_Call {
	return &MockProductRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, productID)}
}

func (_c *MockProductRepository_Delete_Call) Run(run func(ctx context.Context, productID uuid.UUID)) *MockProductRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_Delete_Call) Return(product domain.Product, err error) *MockProductRepository_Delete_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockProductRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, productID uuid.UUID) (domain.Product, error)) *MockProductRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) GetByID(ctx context.Context, productID uuid.UUID) (domain.Product, error) {
	ret := _mock.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Product, error)); ok {
		return returnFunc(ctx, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Product); ok {
		r0 = returnFunc(ctx, productID)
	} else {
		r0 = ret.Get(0).(domain.Product)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockProductRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
func (_e *MockProductRepository_Expecter) GetByID(ctx interface{}, productID interface{}) *MockProductRepository_GetByID_Call {
	return &MockProductRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, productID)}
}

func (_c *MockProductRepository_GetByID_Call) Run(run func(ctx context.Context, productID uuid.UUID)) *MockProductRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_GetByID_Call) Return(product domain.Product, err error) *MockProductRepository_GetByID_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockProductRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, productID uuid.UUID) (domain.Product, error)) *MockProductRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySKU provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) GetBySKU(ctx context.Context, sku string) (domain.Product, error) {
	ret := _mock.Called(ctx, sku)

	if len(ret) == 0 {
		panic("no return value specified for GetBySKU")
	}

	var r0 domain.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Product, error)); ok {
		return returnFunc(ctx, sku)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Product); ok {
		r0 = returnFunc(ctx, sku)
	} else {
		r0 = ret.Get(0).(domain.Product)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, sku)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_GetBySKU_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySKU'
type MockProductRepository_GetBySKU_Call struct {
	*mock.Call
}

// GetBySKU is a helper method to define mock.On call
//   - ctx context.Context
//   - sku string
func (_e *MockProductRepository_Expecter) GetBySKU(ctx interface{}, sku interface{}) *MockProductRepository_GetBySKU_Call {
	return &MockProductRepository_GetBySKU_Call{Call: _e.mock.On("GetBySKU", ctx, sku)}
}

func (_c *MockProductRepository_GetBySKU_Call) Run(run func(ctx context.Context, sku string)) *MockProductRepository_GetBySKU_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_GetBySKU_Call) Return(product domain.Product, err error) *MockProductRepository_GetBySKU_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockProductRepository_GetBySKU_Call) RunAndReturn(run func(ctx context.Context, sku string) (domain.Product, error)) *MockProductRepository_GetBySKU_Call {
	_c.Call.Return(run)
	return _c
}

// GetCurrencyByCode provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) GetCurrencyByCode(ctx context.Context, code string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrencyByCode")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_GetCurrencyByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrencyByCode'
type MockProductRepository_GetCurrencyByCode_Call struct {
	*mock.Call
}

// GetCurrencyByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *MockProductRepository_Expecter) GetCurrencyByCode(ctx interface{}, code interface{}) *MockProductRepository_GetCurrencyByCode_Call {
	return &MockProductRepository_GetCurrencyByCode_Call{Call: _e.mock.On("GetCurrencyByCode", ctx, code)}
}

func (_c *MockProductRepository_GetCurrencyByCode_Call) Run(run func(ctx context.Context, code string)) *MockProductRepository_GetCurrencyByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_GetCurrencyByCode_Call) Return(uUID uuid.UUID, err error) *MockProductRepository_GetCurrencyByCode_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockProductRepository_GetCurrencyByCode_Call) RunAndReturn(run func(ctx context.Context, code string) (uuid.UUID, error)) *MockProductRepository_GetCurrencyByCode_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) List(ctx context.Context, params outbound.ProductListParams) ([]domain.Product, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbound.ProductListParams) ([]domain.Product, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbound.ProductListParams) []domain.Product); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, outbound.ProductListParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockProductRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - params outbound.ProductListParams
func (_e *MockProductRepository_Expecter) List(ctx interface{}, params interface{}) *MockProductRepository_List_Call {
	return &MockProductRepository_List_Call{Call: _e.mock.On("List", ctx, params)}
}

func (_c *MockProductRepository_List_Call) Run(run func(ctx context.Context, params outbound.ProductListParams)) *MockProductRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 outbound.ProductListParams
		if args[1] != nil {
			arg1 = args[1].(outbound.ProductListParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_List_Call) Return(products []domain.Product, err error) *MockProductRepository_List_Call {
	_c.Call.Return(products, err)
	return _c
}

func (_c *MockProductRepository_List_Call) RunAndReturn(run func(ctx context.Context, params outbound.ProductListParams) ([]domain.Product, error)) *MockProductRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) Update(ctx context.Context, product domain.Product) (domain.Product, error) {
	ret := _mock.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Product) (domain.Product, error)); ok {
		return returnFunc(ctx, product)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Product) domain.Product); ok {
		r0 = returnFunc(ctx, product)
	} else {
		r0 = ret.Get(0).(domain.Product)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Product) error); ok {
		r1 = returnFunc(ctx, product)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProductRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - product domain.Product
func (_e *MockProductRepository_Expecter) Update(ctx interface{}, product interface{}) *MockProductRepository_Update_Call {
	return &MockProductRepository_Update_Call{Call: _e.mock.On("Update", ctx, product)}
}

func (_c *MockProductRepository_Update_Call) Run(run func(ctx context.Context, product domain.Product)) *MockProductRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Product
		if args[1] != nil {
			arg1 = args[1].(domain.Product)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_Update_Call) Return(product1 domain.Product, err error) *MockProductRepository_Update_Call {
	_c.Call.Return(product1, err)
	return _c
}

func (_c *MockProductRepository_Update_Call) RunAndReturn(run func(ctx context.Context, product domain.Product) (domain.Product, error)) *MockProductRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStockRepository creates a new instance of MockStockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStockRepository {
	mock := &MockStockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStockRepository is an autogenerated mock type for the StockRepository type
type MockStockRepository struct {
	mock.Mock
}

type MockStockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStockRepository) EXPECT() *MockStockRepository_Expecter {
	return &MockStockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockStockRepository
func (_mock *MockStockRepository) Create(ctx context.Context, stock domain.StockRecord) (domain.StockRecord, error) {
	ret := _mock.Called(ctx, stock)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.StockRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.StockRecord) (domain.StockRecord, error)); ok {
		return returnFunc(ctx, stock)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.StockRecord) domain.StockRecord); ok {
		r0 = returnFunc(ctx, stock)
	} else {
		r0 = ret.Get(0).(domain.StockRecord)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.StockRecord) error); ok {
		r1 = returnFunc(ctx, stock)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - stock domain.StockRecord
func (_e *MockStockRepository_Expecter) Create(ctx interface{}, stock interface{}) *MockStockRepository_Create_Call {
	return &MockStockRepository_Create_Call{Call: _e.mock.On("Create", ctx, stock)}
}

func (_c *MockStockRepository_Create_Call) Run(run func(ctx context.Context, stock domain.StockRecord)) *MockStockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.StockRecord
		if args[1] != nil {
			arg1 = args[1].(domain.StockRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStockRepository_Create_Call) Return(stockRecord domain.StockRecord, err error) *MockStockRepository_Create_Call {
	_c.Call.Return(stockRecord, err)
	return _c
}

func (_c *MockStockRepository_Create_Call) RunAndReturn(run func(ctx context.Context, stock domain.StockRecord) (domain.StockRecord, error)) *MockStockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateReservation provides a mock function for the type MockStockRepository
func (_mock *MockStockRepository) CreateReservation(ctx context.Context, reservation outbound.StockReservation) (outbound.StockReservation, error) {
	ret := _mock.Called(ctx, reservation)

	if len(ret) == 0 {
		panic("no return value specified for CreateReservation")
	}

	var r0 outbound.StockReservation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbound.StockReservation) (outbound.StockReservation, error)); ok {
		return returnFunc(ctx, reservation)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbound.StockReservation) outbound.StockReservation); ok {
		r0 = returnFunc(ctx, reservation)
	} else {
		r0 = ret.Get(0).(outbound.StockReservation)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, outbound.StockReservation) error); ok {
		r1 = returnFunc(ctx, reservation)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStockRepository_CreateReservation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReservation'
type MockStockRepository_CreateReservation_Call struct {
	*mock.Call
}

// CreateReservation is a helper method to define mock.On call
//   - ctx context.Context
//   - reservation outbound.StockReservation
func (_e *MockStockRepository_Expecter) CreateReservation(ctx interface{}, reservation interface{}) *MockStockRepository_CreateReservation_Call {
	return &MockStockRepository_CreateReservation_Call{Call: _e.mock.On("CreateReservation", ctx, reservation)}
}

func (_c *MockStockRepository_CreateReservation_Call) Run(run func(ctx context.Context, reservation outbound.StockReservation)) *MockStockRepository_CreateReservation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 outbound.StockReservation
		if args[1] != nil {
			arg1 = args[1].(outbound.StockReservation)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStockRepository_CreateReservation_Call) Return(stockReservation outbound.StockReservation, err error) *MockStockRepository_CreateReservation_Call {
	_c.Call.Return(stockReservation, err)
	return _c
}

func (_c *MockStockRepository_CreateReservation_Call) RunAndReturn(run func(ctx context.Context, reservation outbound.StockReservation) (outbound.StockReservation, error)) *MockStockRepository_CreateReservation_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteReservationsByOrderID provides a mock function for the type MockStockRepository
func (_mock *MockStockRepository) DeleteReservationsByOrderID(ctx context.Context, orderID uuid.UUID) error {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReservationsByOrderID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStockRepository_DeleteReservationsByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReservationsByOrderID'
type MockStockRepository_DeleteReservationsByOrderID_Call struct {
	*mock.Call
}

// DeleteReservationsByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockStockRepository_Expecter) DeleteReservationsByOrderID(ctx interface{}, orderID interface{}) *MockStockRepository_DeleteReservationsByOrderID_Call {
	return &MockStockRepository_DeleteReservationsByOrderID_Call{Call: _e.mock.On("DeleteReservationsByOrderID", ctx, orderID)}
}

func (_c *MockStockRepository_DeleteReservationsByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockStockRepository_DeleteReservationsByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStockRepository_DeleteReservationsByOrderID_Call) Return(err error) *MockStockRepository_DeleteReservationsByOrderID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStockRepository_DeleteReservationsByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) error) *MockStockRepository_DeleteReservationsByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByProductID provides a mock function for the type MockStockRepository
func (_mock *MockStockRepository) GetByProductID(ctx context.Context, productID uuid.UUID) (domain.StockRecord, error) {
	ret := _mock.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetByProductID")
	}

	var r0 domain.StockRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.StockRecord, error)); ok {
		return returnFunc(ctx, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.StockRecord); ok {
		r0 = returnFunc(ctx, productID)
	} else {
		r0 = ret.Get(0).(domain.StockRecord)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStockRepository_GetByProductID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProductID'
type MockStockRepository_GetByProductID_Call struct {
	*mock.Call
}

// GetByProductID is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
func (_e *MockStockRepository_Expecter) GetByProductID(ctx interface{}, productID interface{}) *MockStockRepository_GetByProductID_Call {
	return &MockStockRepository_GetByProductID_Call{Call: _e.mock.On("GetByProductID", ctx, productID)}
}

func (_c *MockStockRepository_GetByProductID_Call) Run(run func(ctx context.Context, productID uuid.UUID)) *MockStockRepository_GetByProductID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStockRepository_GetByProductID_Call) Return(stockRecord domain.StockRecord, err error) *MockStockRepository_GetByProductID_Call {
	_c.Call.Return(stockRecord, err)
	return _c
}

func (_c *MockStockRepository_GetByProductID_Call) RunAndReturn(run func(ctx context.Context, productID uuid.UUID) (domain.StockRecord, error)) *MockStockRepository_GetByProductID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByProductIDForUpdate provides a mock function for the type MockStockRepository
func (_mock *MockStockRepository) GetByProductIDForUpdate(ctx context.Context, productID uuid.UUID) (domain.StockRecord, error) {
	ret := _mock.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetByProductIDForUpdate")
	}

	var r0 domain.StockRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.StockRecord, error)); ok {
		return returnFunc(ctx, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.StockRecord); ok {
		r0 = returnFunc(ctx, productID)
	} else {
		r0 = ret.Get(0).(domain.StockRecord)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStockRepository_GetByProductIDForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByProductIDForUpdate'
type MockStockRepository_GetByProductIDForUpdate_Call struct {
	*mock.Call
}

// GetByProductIDForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - productID uuid.UUID
func (_e *MockStockRepository_Expecter) GetByProductIDForUpdate(ctx interface{}, productID interface{}) *MockStockRepository_GetByProductIDForUpdate_Call {
	return &MockStockRepository_GetByProductIDForUpdate_Call{Call: _e.mock.On("GetByProductIDForUpdate", ctx, productID)}
}

func (_c *MockStockRepository_GetByProductIDForUpdate_Call) Run(run func(ctx context.Context, productID uuid.UUID)) *MockStockRepository_GetByProductIDForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStockRepository_GetByProductIDForUpdate_Call) Return(stockRecord domain.StockRecord, err error) *MockStockRepository_GetByProductIDForUpdate_Call {
	_c.Call.Return(stockRecord, err)
	return _c
}

func (_c *MockStockRepository_GetByProductIDForUpdate_Call) RunAndReturn(run func(ctx context.Context, productID uuid.UUID) (domain.StockRecord, error)) *MockStockRepository_GetByProductIDForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// ListReservationsByOrderID provides a mock function for the type MockStockRepository
func (_mock *MockStockRepository) ListReservationsByOrderID(ctx context.Context, orderID uuid.UUID) ([]outbound.StockReservation, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for ListReservationsByOrderID")
	}

	var r0 []outbound.StockReservation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]outbound.StockReservation, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []outbound.StockReservation); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]outbound.StockReservation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStockRepository_ListReservationsByOrderID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReservationsByOrderID'
type MockStockRepository_ListReservationsByOrderID_Call struct {
	*mock.Call
}

// ListReservationsByOrderID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockStockRepository_Expecter) ListReservationsByOrderID(ctx interface{}, orderID interface{}) *MockStockRepository_ListReservationsByOrderID_Call {
	return &MockStockRepository_ListReservationsByOrderID_Call{Call: _e.mock.On("ListReservationsByOrderID", ctx, orderID)}
}

func (_c *MockStockRepository_ListReservationsByOrderID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockStockRepository_ListReservationsByOrderID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStockRepository_ListReservationsByOrderID_Call) Return(stockReservations []outbound.StockReservation, err error) *MockStockRepository_ListReservationsByOrderID_Call {
	_c.Call.Return(stockReservations, err)
	return _c
}

func (_c *MockStockRepository_ListReservationsByOrderID_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) ([]outbound.StockReservation, error)) *MockStockRepository_ListReservationsByOrderID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockStockRepository
func (_mock *MockStockRepository) Update(ctx context.Context, stock domain.StockRecord) (domain.StockRecord, error) {
	ret := _mock.Called(ctx, stock)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.StockRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.StockRecord) (domain.StockRecord, error)); ok {
		return returnFunc(ctx, stock)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.StockRecord) domain.StockRecord); ok {
		r0 = returnFunc(ctx, stock)
	} else {
		r0 = ret.Get(0).(domain.StockRecord)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.StockRecord) error); ok {
		r1 = returnFunc(ctx, stock)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStockRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStockRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - stock domain.StockRecord
func (_e *MockStockRepository_Expecter) Update(ctx interface{}, stock interface{}) *MockStockRepository_Update_Call {
	return &MockStockRepository_Update_Call{Call: _e.mock.On("Update", ctx, stock)}
}

func (_c *MockStockRepository_Update_Call) Run(run func(ctx context.Context, stock domain.StockRecord)) *MockStockRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.StockRecord
		if args[1] != nil {
			arg1 = args[1].(domain.StockRecord)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStockRepository_Update_Call) Return(stockRecord domain.StockRecord, err error) *MockStockRepository_Update_Call {
	_c.Call.Return(stockRecord, err)
	return _c
}

func (_c *MockStockRepository_Update_Call) RunAndReturn(run func(ctx context.Context, stock domain.StockRecord) (domain.StockRecord, error)) *MockStockRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
