// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consumer_idempotency.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const consumerIdempotencyExists = `-- name: ConsumerIdempotencyExists :one
SELECT
  EXISTS (
    SELECT
      1
    FROM
      consumer_idempotency
    WHERE
      event_id = $1
      AND consumer_group_name = $2
  )
`

type ConsumerIdempotencyExistsParams struct {
	EventID           uuid.UUID
	ConsumerGroupName string
}

func (q *Queries) ConsumerIdempotencyExists(ctx context.Context, arg ConsumerIdempotencyExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, consumerIdempotencyExists, arg.EventID, arg.ConsumerGroupName)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createConsumerIdempotency = `-- name: CreateConsumerIdempotency :exec
INSERT INTO
  consumer_idempotency (event_id, consumer_group_name, delivery_request_id)
VALUES
  (
    $1,
    $2,
    $3
  )
`

type CreateConsumerIdempotencyParams struct {
	EventID           uuid.UUID
	ConsumerGroupName string
	DeliveryRequestID uuid.UUID
}

func (q *Queries) CreateConsumerIdempotency(ctx context.Context, arg CreateConsumerIdempotencyParams) error {
	_, err := q.db.ExecContext(ctx, createConsumerIdempotency, arg.EventID, arg.ConsumerGroupName, arg.DeliveryRequestID)
	return err
}
