// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delivery_attempts.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createDeliveryAttempt = `-- name: CreateDeliveryAttempt :one
INSERT INTO
  delivery_attempts (
    delivery_request_id,
    attempt_number,
    provider_name,
    provider_message_id,
    failure_code,
    failure_message,
    attempted_at
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
  )
RETURNING
  delivery_attempt_id, delivery_request_id, attempt_number, provider_name, provider_message_id, failure_code, failure_message, attempted_at, created_at
`

type CreateDeliveryAttemptParams struct {
	DeliveryRequestID uuid.UUID
	AttemptNumber     int32
	ProviderName      string
	ProviderMessageID string
	FailureCode       sql.NullString
	FailureMessage    sql.NullString
	AttemptedAt       time.Time
}

func (q *Queries) CreateDeliveryAttempt(ctx context.Context, arg CreateDeliveryAttemptParams) (DeliveryAttempt, error) {
	row := q.db.QueryRowContext(ctx, createDeliveryAttempt,
		arg.DeliveryRequestID,
		arg.AttemptNumber,
		arg.ProviderName,
		arg.ProviderMessageID,
		arg.FailureCode,
		arg.FailureMessage,
		arg.AttemptedAt,
	)
	var i DeliveryAttempt
	err := row.Scan(
		&i.DeliveryAttemptID,
		&i.DeliveryRequestID,
		&i.AttemptNumber,
		&i.ProviderName,
		&i.ProviderMessageID,
		&i.FailureCode,
		&i.FailureMessage,
		&i.AttemptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listDeliveryAttemptsByDeliveryRequestID = `-- name: ListDeliveryAttemptsByDeliveryRequestID :many
SELECT
  delivery_attempt_id, delivery_request_id, attempt_number, provider_name, provider_message_id, failure_code, failure_message, attempted_at, created_at
FROM
  delivery_attempts
WHERE
  delivery_request_id = $1
ORDER BY
  attempt_number ASC
`

func (q *Queries) ListDeliveryAttemptsByDeliveryRequestID(ctx context.Context, deliveryRequestID uuid.UUID) ([]DeliveryAttempt, error) {
	rows, err := q.db.QueryContext(ctx, listDeliveryAttemptsByDeliveryRequestID, deliveryRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeliveryAttempt
	for rows.Next() {
		var i DeliveryAttempt
		if err := rows.Scan(
			&i.DeliveryAttemptID,
			&i.DeliveryRequestID,
			&i.AttemptNumber,
			&i.ProviderName,
			&i.ProviderMessageID,
			&i.FailureCode,
			&i.FailureMessage,
			&i.AttemptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
