// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delivery_requests.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createRequestedDeliveryRequest = `-- name: CreateRequestedDeliveryRequest :one
INSERT INTO
  delivery_requests (
    source_event_id,
    correlation_id,
    source_event_name,
    channel,
    recipient,
    template_key,
    status,
    idempotency_key
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
  )
RETURNING
  delivery_request_id, source_event_id, correlation_id, source_event_name, channel, recipient, template_key, status, idempotency_key, last_error_code, last_error_message, created_at, updated_at
`

type CreateRequestedDeliveryRequestParams struct {
	SourceEventID   uuid.UUID
	CorrelationID   string
	SourceEventName string
	Channel         string
	Recipient       string
	TemplateKey     string
	Status          DeliveryStatus
	IdempotencyKey  string
}

func (q *Queries) CreateRequestedDeliveryRequest(ctx context.Context, arg CreateRequestedDeliveryRequestParams) (DeliveryRequest, error) {
	row := q.db.QueryRowContext(ctx, createRequestedDeliveryRequest,
		arg.SourceEventID,
		arg.CorrelationID,
		arg.SourceEventName,
		arg.Channel,
		arg.Recipient,
		arg.TemplateKey,
		arg.Status,
		arg.IdempotencyKey,
	)
	var i DeliveryRequest
	err := row.Scan(
		&i.DeliveryRequestID,
		&i.SourceEventID,
		&i.CorrelationID,
		&i.SourceEventName,
		&i.Channel,
		&i.Recipient,
		&i.TemplateKey,
		&i.Status,
		&i.IdempotencyKey,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeliveryRequestByID = `-- name: GetDeliveryRequestByID :one
SELECT
  delivery_request_id, source_event_id, correlation_id, source_event_name, channel, recipient, template_key, status, idempotency_key, last_error_code, last_error_message, created_at, updated_at
FROM
  delivery_requests
WHERE
  delivery_request_id = $1
LIMIT
  1
`

func (q *Queries) GetDeliveryRequestByID(ctx context.Context, deliveryRequestID uuid.UUID) (DeliveryRequest, error) {
	row := q.db.QueryRowContext(ctx, getDeliveryRequestByID, deliveryRequestID)
	var i DeliveryRequest
	err := row.Scan(
		&i.DeliveryRequestID,
		&i.SourceEventID,
		&i.CorrelationID,
		&i.SourceEventName,
		&i.Channel,
		&i.Recipient,
		&i.TemplateKey,
		&i.Status,
		&i.IdempotencyKey,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeliveryRequestByIdempotencyKey = `-- name: GetDeliveryRequestByIdempotencyKey :one
SELECT
  delivery_request_id, source_event_id, correlation_id, source_event_name, channel, recipient, template_key, status, idempotency_key, last_error_code, last_error_message, created_at, updated_at
FROM
  delivery_requests
WHERE
  idempotency_key = $1
LIMIT
  1
`

func (q *Queries) GetDeliveryRequestByIdempotencyKey(ctx context.Context, idempotencyKey string) (DeliveryRequest, error) {
	row := q.db.QueryRowContext(ctx, getDeliveryRequestByIdempotencyKey, idempotencyKey)
	var i DeliveryRequest
	err := row.Scan(
		&i.DeliveryRequestID,
		&i.SourceEventID,
		&i.CorrelationID,
		&i.SourceEventName,
		&i.Channel,
		&i.Recipient,
		&i.TemplateKey,
		&i.Status,
		&i.IdempotencyKey,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDeliveryRequestFailed = `-- name: MarkDeliveryRequestFailed :one
UPDATE delivery_requests
SET
  status = $1,
  last_error_code = $2,
  last_error_message = $3,
  updated_at = now()
WHERE
  delivery_request_id = $4
RETURNING
  delivery_request_id, source_event_id, correlation_id, source_event_name, channel, recipient, template_key, status, idempotency_key, last_error_code, last_error_message, created_at, updated_at
`

type MarkDeliveryRequestFailedParams struct {
	Status            DeliveryStatus
	LastErrorCode     sql.NullString
	LastErrorMessage  sql.NullString
	DeliveryRequestID uuid.UUID
}

func (q *Queries) MarkDeliveryRequestFailed(ctx context.Context, arg MarkDeliveryRequestFailedParams) (DeliveryRequest, error) {
	row := q.db.QueryRowContext(ctx, markDeliveryRequestFailed,
		arg.Status,
		arg.LastErrorCode,
		arg.LastErrorMessage,
		arg.DeliveryRequestID,
	)
	var i DeliveryRequest
	err := row.Scan(
		&i.DeliveryRequestID,
		&i.SourceEventID,
		&i.CorrelationID,
		&i.SourceEventName,
		&i.Channel,
		&i.Recipient,
		&i.TemplateKey,
		&i.Status,
		&i.IdempotencyKey,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markDeliveryRequestSent = `-- name: MarkDeliveryRequestSent :one
UPDATE delivery_requests
SET
  status = $1,
  last_error_code = NULL,
  last_error_message = NULL,
  updated_at = now()
WHERE
  delivery_request_id = $2
RETURNING
  delivery_request_id, source_event_id, correlation_id, source_event_name, channel, recipient, template_key, status, idempotency_key, last_error_code, last_error_message, created_at, updated_at
`

type MarkDeliveryRequestSentParams struct {
	Status            DeliveryStatus
	DeliveryRequestID uuid.UUID
}

func (q *Queries) MarkDeliveryRequestSent(ctx context.Context, arg MarkDeliveryRequestSentParams) (DeliveryRequest, error) {
	row := q.db.QueryRowContext(ctx, markDeliveryRequestSent, arg.Status, arg.DeliveryRequestID)
	var i DeliveryRequest
	err := row.Scan(
		&i.DeliveryRequestID,
		&i.SourceEventID,
		&i.CorrelationID,
		&i.SourceEventName,
		&i.Channel,
		&i.Recipient,
		&i.TemplateKey,
		&i.Status,
		&i.IdempotencyKey,
		&i.LastErrorCode,
		&i.LastErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
