// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type DeliveryStatus string

const (
	DeliveryStatusRequested DeliveryStatus = "requested"
	DeliveryStatusSent      DeliveryStatus = "sent"
	DeliveryStatusFailed    DeliveryStatus = "failed"
)

func (e *DeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryStatus(s)
	case string:
		*e = DeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryStatus: %T", src)
	}
	return nil
}

type NullDeliveryStatus struct {
	DeliveryStatus DeliveryStatus
	Valid          bool // Valid is true if DeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryStatus), nil
}

type ConsumerIdempotency struct {
	EventID           uuid.UUID
	ConsumerGroupName string
	DeliveryRequestID uuid.UUID
	CreatedAt         time.Time
}

type DeliveryAttempt struct {
	DeliveryAttemptID uuid.UUID
	DeliveryRequestID uuid.UUID
	AttemptNumber     int32
	ProviderName      string
	ProviderMessageID string
	FailureCode       sql.NullString
	FailureMessage    sql.NullString
	AttemptedAt       time.Time
	CreatedAt         time.Time
}

type DeliveryRequest struct {
	DeliveryRequestID uuid.UUID
	SourceEventID     uuid.UUID
	CorrelationID     string
	SourceEventName   string
	Channel           string
	Recipient         string
	TemplateKey       string
	Status            DeliveryStatus
	IdempotencyKey    string
	LastErrorCode     sql.NullString
	LastErrorMessage  sql.NullString
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type OutboxRecord struct {
	ID            uuid.UUID
	EventID       uuid.UUID
	EventName     string
	AggregateType string
	AggregateID   string
	Topic         string
	Key           []byte
	Payload       []byte
	Headers       json.RawMessage
	Attempt       int32
	Status        interface{}
	LastError     sql.NullString
	NextAttemptAt time.Time
	LockedAt      sql.NullTime
	LockedBy      sql.NullString
	PublishedAt   sql.NullTime
	MaxAttempts   int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
