// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ConsumerIdempotencyExists(ctx context.Context, arg ConsumerIdempotencyExistsParams) (bool, error)
	CreateConsumerIdempotency(ctx context.Context, arg CreateConsumerIdempotencyParams) error
	CreateDeliveryAttempt(ctx context.Context, arg CreateDeliveryAttemptParams) (DeliveryAttempt, error)
	CreateRequestedDeliveryRequest(ctx context.Context, arg CreateRequestedDeliveryRequestParams) (DeliveryRequest, error)
	GetDeliveryRequestByID(ctx context.Context, deliveryRequestID uuid.UUID) (DeliveryRequest, error)
	GetDeliveryRequestByIdempotencyKey(ctx context.Context, idempotencyKey string) (DeliveryRequest, error)
	ListDeliveryAttemptsByDeliveryRequestID(ctx context.Context, deliveryRequestID uuid.UUID) ([]DeliveryAttempt, error)
	MarkDeliveryRequestFailed(ctx context.Context, arg MarkDeliveryRequestFailedParams) (DeliveryRequest, error)
	MarkDeliveryRequestSent(ctx context.Context, arg MarkDeliveryRequestSentParams) (DeliveryRequest, error)
}

var _ Querier = (*Queries)(nil)
