// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AppendOutboxRecord(ctx context.Context, arg AppendOutboxRecordParams) (OutboxRecord, error)
	ClaimPendingOutboxRecords(ctx context.Context, arg ClaimPendingOutboxRecordsParams) ([]OutboxRecord, error)
	ClaimStaleInProgressOutboxRecords(ctx context.Context, arg ClaimStaleInProgressOutboxRecordsParams) ([]OutboxRecord, error)
	ConsumerIdempotencyExists(ctx context.Context, arg ConsumerIdempotencyExistsParams) (bool, error)
	CreateConsumerIdempotency(ctx context.Context, arg CreateConsumerIdempotencyParams) error
	CreateDeliveryAttempt(ctx context.Context, arg CreateDeliveryAttemptParams) (DeliveryAttempt, error)
	CreateRequestedDeliveryRequest(ctx context.Context, arg CreateRequestedDeliveryRequestParams) (DeliveryRequest, error)
	GetDeliveryRequestByID(ctx context.Context, deliveryRequestID uuid.UUID) (DeliveryRequest, error)
	GetDeliveryRequestByIdempotencyKey(ctx context.Context, idempotencyKey string) (DeliveryRequest, error)
	ListDeliveryAttemptsByDeliveryRequestID(ctx context.Context, deliveryRequestID uuid.UUID) ([]DeliveryAttempt, error)
	MarkDeliveryRequestFailed(ctx context.Context, arg MarkDeliveryRequestFailedParams) (DeliveryRequest, error)
	MarkDeliveryRequestSent(ctx context.Context, arg MarkDeliveryRequestSentParams) (DeliveryRequest, error)
	MarkOutboxRecordDead(ctx context.Context, arg MarkOutboxRecordDeadParams) (int64, error)
	MarkOutboxRecordPublished(ctx context.Context, arg MarkOutboxRecordPublishedParams) (int64, error)
	MarkOutboxRecordRetryableFailure(ctx context.Context, arg MarkOutboxRecordRetryableFailureParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
