services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otelcol-contrib/config.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
      - "13133:13133"
    volumes:
      - ${PWD}/configs/otel/otel-collector.yaml:/etc/otelcol-contrib/config.yaml:ro
    healthcheck:
      test: ["CMD", "/otelcol-contrib", "--version"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    restart: unless-stopped
    networks:
      - observability

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/configs/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    healthcheck:
      test: ["CMD", "/bin/prometheus", "--version"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    restart: unless-stopped
    networks:
      - observability

  tempo:
    image: grafana/tempo:latest
    command:
      [
        "-storage.trace.backend=local",
        "-storage.trace.local.path=/tmp/tempo/traces",
        "-ingest.topic=tempo",
        "-generator.topic=tempo",
      ]
    expose:
      - "4317"
    ports:
      - "3200:3200"
      - "14268:14268"
    healthcheck:
      test: ["CMD", "/tempo", "-version"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    restart: unless-stopped
    networks:
      - observability

  loki:
    image: grafana/loki:latest
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100"
    healthcheck:
      test: ["CMD", "/usr/bin/loki", "-version"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 15s
    restart: unless-stopped
    networks:
      - observability

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    healthcheck:
      test: ["CMD", "/run.sh", "-v"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    restart: unless-stopped
    networks:
      - observability

networks:
  observability:
