// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package outboundmocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/shrtyk/e-commerce-platform/internal/notification-svc/internal/core/domain"
	"github.com/shrtyk/e-commerce-platform/internal/notification-svc/internal/core/ports/outbound"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConsumerIdempotencyRepository creates a new instance of MockConsumerIdempotencyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumerIdempotencyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumerIdempotencyRepository {
	mock := &MockConsumerIdempotencyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConsumerIdempotencyRepository is an autogenerated mock type for the ConsumerIdempotencyRepository type
type MockConsumerIdempotencyRepository struct {
	mock.Mock
}

type MockConsumerIdempotencyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsumerIdempotencyRepository) EXPECT() *MockConsumerIdempotencyRepository_Expecter {
	return &MockConsumerIdempotencyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockConsumerIdempotencyRepository
func (_mock *MockConsumerIdempotencyRepository) Create(ctx context.Context, input outbound.CreateConsumerIdempotencyInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbound.CreateConsumerIdempotencyInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConsumerIdempotencyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockConsumerIdempotencyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input outbound.CreateConsumerIdempotencyInput
func (_e *MockConsumerIdempotencyRepository_Expecter) Create(ctx interface{}, input interface{}) *MockConsumerIdempotencyRepository_Create_Call {
	return &MockConsumerIdempotencyRepository_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockConsumerIdempotencyRepository_Create_Call) Run(run func(ctx context.Context, input outbound.CreateConsumerIdempotencyInput)) *MockConsumerIdempotencyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 outbound.CreateConsumerIdempotencyInput
		if args[1] != nil {
			arg1 = args[1].(outbound.CreateConsumerIdempotencyInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConsumerIdempotencyRepository_Create_Call) Return(err error) *MockConsumerIdempotencyRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConsumerIdempotencyRepository_Create_Call) RunAndReturn(run func(ctx context.Context, input outbound.CreateConsumerIdempotencyInput) error) *MockConsumerIdempotencyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockConsumerIdempotencyRepository
func (_mock *MockConsumerIdempotencyRepository) Exists(ctx context.Context, eventID uuid.UUID, consumerGroupName string) (bool, error) {
	ret := _mock.Called(ctx, eventID, consumerGroupName)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (bool, error)); ok {
		return returnFunc(ctx, eventID, consumerGroupName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) bool); ok {
		r0 = returnFunc(ctx, eventID, consumerGroupName)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, eventID, consumerGroupName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockConsumerIdempotencyRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockConsumerIdempotencyRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - eventID uuid.UUID
//   - consumerGroupName string
func (_e *MockConsumerIdempotencyRepository_Expecter) Exists(ctx interface{}, eventID interface{}, consumerGroupName interface{}) *MockConsumerIdempotencyRepository_Exists_Call {
	return &MockConsumerIdempotencyRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, eventID, consumerGroupName)}
}

func (_c *MockConsumerIdempotencyRepository_Exists_Call) Run(run func(ctx context.Context, eventID uuid.UUID, consumerGroupName string)) *MockConsumerIdempotencyRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockConsumerIdempotencyRepository_Exists_Call) Return(b bool, err error) *MockConsumerIdempotencyRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockConsumerIdempotencyRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, eventID uuid.UUID, consumerGroupName string) (bool, error)) *MockConsumerIdempotencyRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeliveryAttemptRepository creates a new instance of MockDeliveryAttemptRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeliveryAttemptRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeliveryAttemptRepository {
	mock := &MockDeliveryAttemptRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeliveryAttemptRepository is an autogenerated mock type for the DeliveryAttemptRepository type
type MockDeliveryAttemptRepository struct {
	mock.Mock
}

type MockDeliveryAttemptRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeliveryAttemptRepository) EXPECT() *MockDeliveryAttemptRepository_Expecter {
	return &MockDeliveryAttemptRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockDeliveryAttemptRepository
func (_mock *MockDeliveryAttemptRepository) Create(ctx context.Context, input outbound.CreateDeliveryAttemptInput) (domain.DeliveryAttempt, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.DeliveryAttempt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbound.CreateDeliveryAttemptInput) (domain.DeliveryAttempt, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbound.CreateDeliveryAttemptInput) domain.DeliveryAttempt); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(domain.DeliveryAttempt)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, outbound.CreateDeliveryAttemptInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeliveryAttemptRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDeliveryAttemptRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input outbound.CreateDeliveryAttemptInput
func (_e *MockDeliveryAttemptRepository_Expecter) Create(ctx interface{}, input interface{}) *MockDeliveryAttemptRepository_Create_Call {
	return &MockDeliveryAttemptRepository_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *MockDeliveryAttemptRepository_Create_Call) Run(run func(ctx context.Context, input outbound.CreateDeliveryAttemptInput)) *MockDeliveryAttemptRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 outbound.CreateDeliveryAttemptInput
		if args[1] != nil {
			arg1 = args[1].(outbound.CreateDeliveryAttemptInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeliveryAttemptRepository_Create_Call) Return(deliveryAttempt domain.DeliveryAttempt, err error) *MockDeliveryAttemptRepository_Create_Call {
	_c.Call.Return(deliveryAttempt, err)
	return _c
}

func (_c *MockDeliveryAttemptRepository_Create_Call) RunAndReturn(run func(ctx context.Context, input outbound.CreateDeliveryAttemptInput) (domain.DeliveryAttempt, error)) *MockDeliveryAttemptRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ListByDeliveryRequestID provides a mock function for the type MockDeliveryAttemptRepository
func (_mock *MockDeliveryAttemptRepository) ListByDeliveryRequestID(ctx context.Context, deliveryRequestID uuid.UUID) ([]domain.DeliveryAttempt, error) {
	ret := _mock.Called(ctx, deliveryRequestID)

	if len(ret) == 0 {
		panic("no return value specified for ListByDeliveryRequestID")
	}

	var r0 []domain.DeliveryAttempt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.DeliveryAttempt, error)); ok {
		return returnFunc(ctx, deliveryRequestID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.DeliveryAttempt); ok {
		r0 = returnFunc(ctx, deliveryRequestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DeliveryAttempt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, deliveryRequestID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeliveryAttemptRepository_ListByDeliveryRequestID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByDeliveryRequestID'
type MockDeliveryAttemptRepository_ListByDeliveryRequestID_Call struct {
	*mock.Call
}

// ListByDeliveryRequestID is a helper method to define mock.On call
//   - ctx context.Context
//   - deliveryRequestID uuid.UUID
func (_e *MockDeliveryAttemptRepository_Expecter) ListByDeliveryRequestID(ctx interface{}, deliveryRequestID interface{}) *MockDeliveryAttemptRepository_ListByDeliveryRequestID_Call {
	return &MockDeliveryAttemptRepository_ListByDeliveryRequestID_Call{Call: _e.mock.On("ListByDeliveryRequestID", ctx, deliveryRequestID)}
}

func (_c *MockDeliveryAttemptRepository_ListByDeliveryRequestID_Call) Run(run func(ctx context.Context, deliveryRequestID uuid.UUID)) *MockDeliveryAttemptRepository_ListByDeliveryRequestID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeliveryAttemptRepository_ListByDeliveryRequestID_Call) Return(deliveryAttempts []domain.DeliveryAttempt, err error) *MockDeliveryAttemptRepository_ListByDeliveryRequestID_Call {
	_c.Call.Return(deliveryAttempts, err)
	return _c
}

func (_c *MockDeliveryAttemptRepository_ListByDeliveryRequestID_Call) RunAndReturn(run func(ctx context.Context, deliveryRequestID uuid.UUID) ([]domain.DeliveryAttempt, error)) *MockDeliveryAttemptRepository_ListByDeliveryRequestID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeliveryProvider creates a new instance of MockDeliveryProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeliveryProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeliveryProvider {
	mock := &MockDeliveryProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeliveryProvider is an autogenerated mock type for the DeliveryProvider type
type MockDeliveryProvider struct {
	mock.Mock
}

type MockDeliveryProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeliveryProvider) EXPECT() *MockDeliveryProvider_Expecter {
	return &MockDeliveryProvider_Expecter{mock: &_m.Mock}
}

// Send provides a mock function for the type MockDeliveryProvider
func (_mock *MockDeliveryProvider) Send(ctx context.Context, input outbound.SendDeliveryInput) (outbound.SendDeliveryResult, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 outbound.SendDeliveryResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbound.SendDeliveryInput) (outbound.SendDeliveryResult, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbound.SendDeliveryInput) outbound.SendDeliveryResult); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(outbound.SendDeliveryResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, outbound.SendDeliveryInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeliveryProvider_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockDeliveryProvider_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - input outbound.SendDeliveryInput
func (_e *MockDeliveryProvider_Expecter) Send(ctx interface{}, input interface{}) *MockDeliveryProvider_Send_Call {
	return &MockDeliveryProvider_Send_Call{Call: _e.mock.On("Send", ctx, input)}
}

func (_c *MockDeliveryProvider_Send_Call) Run(run func(ctx context.Context, input outbound.SendDeliveryInput)) *MockDeliveryProvider_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 outbound.SendDeliveryInput
		if args[1] != nil {
			arg1 = args[1].(outbound.SendDeliveryInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeliveryProvider_Send_Call) Return(sendDeliveryResult outbound.SendDeliveryResult, err error) *MockDeliveryProvider_Send_Call {
	_c.Call.Return(sendDeliveryResult, err)
	return _c
}

func (_c *MockDeliveryProvider_Send_Call) RunAndReturn(run func(ctx context.Context, input outbound.SendDeliveryInput) (outbound.SendDeliveryResult, error)) *MockDeliveryProvider_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeliveryRequestRepository creates a new instance of MockDeliveryRequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeliveryRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeliveryRequestRepository {
	mock := &MockDeliveryRequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDeliveryRequestRepository is an autogenerated mock type for the DeliveryRequestRepository type
type MockDeliveryRequestRepository struct {
	mock.Mock
}

type MockDeliveryRequestRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeliveryRequestRepository) EXPECT() *MockDeliveryRequestRepository_Expecter {
	return &MockDeliveryRequestRepository_Expecter{mock: &_m.Mock}
}

// CreateRequested provides a mock function for the type MockDeliveryRequestRepository
func (_mock *MockDeliveryRequestRepository) CreateRequested(ctx context.Context, input outbound.CreateDeliveryRequestInput) (domain.DeliveryRequest, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateRequested")
	}

	var r0 domain.DeliveryRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbound.CreateDeliveryRequestInput) (domain.DeliveryRequest, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbound.CreateDeliveryRequestInput) domain.DeliveryRequest); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(domain.DeliveryRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, outbound.CreateDeliveryRequestInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeliveryRequestRepository_CreateRequested_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRequested'
type MockDeliveryRequestRepository_CreateRequested_Call struct {
	*mock.Call
}

// CreateRequested is a helper method to define mock.On call
//   - ctx context.Context
//   - input outbound.CreateDeliveryRequestInput
func (_e *MockDeliveryRequestRepository_Expecter) CreateRequested(ctx interface{}, input interface{}) *MockDeliveryRequestRepository_CreateRequested_Call {
	return &MockDeliveryRequestRepository_CreateRequested_Call{Call: _e.mock.On("CreateRequested", ctx, input)}
}

func (_c *MockDeliveryRequestRepository_CreateRequested_Call) Run(run func(ctx context.Context, input outbound.CreateDeliveryRequestInput)) *MockDeliveryRequestRepository_CreateRequested_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 outbound.CreateDeliveryRequestInput
		if args[1] != nil {
			arg1 = args[1].(outbound.CreateDeliveryRequestInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeliveryRequestRepository_CreateRequested_Call) Return(deliveryRequest domain.DeliveryRequest, err error) *MockDeliveryRequestRepository_CreateRequested_Call {
	_c.Call.Return(deliveryRequest, err)
	return _c
}

func (_c *MockDeliveryRequestRepository_CreateRequested_Call) RunAndReturn(run func(ctx context.Context, input outbound.CreateDeliveryRequestInput) (domain.DeliveryRequest, error)) *MockDeliveryRequestRepository_CreateRequested_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockDeliveryRequestRepository
func (_mock *MockDeliveryRequestRepository) GetByID(ctx context.Context, deliveryRequestID uuid.UUID) (domain.DeliveryRequest, error) {
	ret := _mock.Called(ctx, deliveryRequestID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.DeliveryRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.DeliveryRequest, error)); ok {
		return returnFunc(ctx, deliveryRequestID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.DeliveryRequest); ok {
		r0 = returnFunc(ctx, deliveryRequestID)
	} else {
		r0 = ret.Get(0).(domain.DeliveryRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, deliveryRequestID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeliveryRequestRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockDeliveryRequestRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - deliveryRequestID uuid.UUID
func (_e *MockDeliveryRequestRepository_Expecter) GetByID(ctx interface{}, deliveryRequestID interface{}) *MockDeliveryRequestRepository_GetByID_Call {
	return &MockDeliveryRequestRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, deliveryRequestID)}
}

func (_c *MockDeliveryRequestRepository_GetByID_Call) Run(run func(ctx context.Context, deliveryRequestID uuid.UUID)) *MockDeliveryRequestRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeliveryRequestRepository_GetByID_Call) Return(deliveryRequest domain.DeliveryRequest, err error) *MockDeliveryRequestRepository_GetByID_Call {
	_c.Call.Return(deliveryRequest, err)
	return _c
}

func (_c *MockDeliveryRequestRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, deliveryRequestID uuid.UUID) (domain.DeliveryRequest, error)) *MockDeliveryRequestRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIdempotencyKey provides a mock function for the type MockDeliveryRequestRepository
func (_mock *MockDeliveryRequestRepository) GetByIdempotencyKey(ctx context.Context, idempotencyKey string) (domain.DeliveryRequest, error) {
	ret := _mock.Called(ctx, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for GetByIdempotencyKey")
	}

	var r0 domain.DeliveryRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.DeliveryRequest, error)); ok {
		return returnFunc(ctx, idempotencyKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.DeliveryRequest); ok {
		r0 = returnFunc(ctx, idempotencyKey)
	} else {
		r0 = ret.Get(0).(domain.DeliveryRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeliveryRequestRepository_GetByIdempotencyKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIdempotencyKey'
type MockDeliveryRequestRepository_GetByIdempotencyKey_Call struct {
	*mock.Call
}

// GetByIdempotencyKey is a helper method to define mock.On call
//   - ctx context.Context
//   - idempotencyKey string
func (_e *MockDeliveryRequestRepository_Expecter) GetByIdempotencyKey(ctx interface{}, idempotencyKey interface{}) *MockDeliveryRequestRepository_GetByIdempotencyKey_Call {
	return &MockDeliveryRequestRepository_GetByIdempotencyKey_Call{Call: _e.mock.On("GetByIdempotencyKey", ctx, idempotencyKey)}
}

func (_c *MockDeliveryRequestRepository_GetByIdempotencyKey_Call) Run(run func(ctx context.Context, idempotencyKey string)) *MockDeliveryRequestRepository_GetByIdempotencyKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeliveryRequestRepository_GetByIdempotencyKey_Call) Return(deliveryRequest domain.DeliveryRequest, err error) *MockDeliveryRequestRepository_GetByIdempotencyKey_Call {
	_c.Call.Return(deliveryRequest, err)
	return _c
}

func (_c *MockDeliveryRequestRepository_GetByIdempotencyKey_Call) RunAndReturn(run func(ctx context.Context, idempotencyKey string) (domain.DeliveryRequest, error)) *MockDeliveryRequestRepository_GetByIdempotencyKey_Call {
	_c.Call.Return(run)
	return _c
}

// MarkFailed provides a mock function for the type MockDeliveryRequestRepository
func (_mock *MockDeliveryRequestRepository) MarkFailed(ctx context.Context, deliveryRequestID uuid.UUID, failureCode string, failureMessage string) (domain.DeliveryRequest, error) {
	ret := _mock.Called(ctx, deliveryRequestID, failureCode, failureMessage)

	if len(ret) == 0 {
		panic("no return value specified for MarkFailed")
	}

	var r0 domain.DeliveryRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) (domain.DeliveryRequest, error)); ok {
		return returnFunc(ctx, deliveryRequestID, failureCode, failureMessage)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) domain.DeliveryRequest); ok {
		r0 = returnFunc(ctx, deliveryRequestID, failureCode, failureMessage)
	} else {
		r0 = ret.Get(0).(domain.DeliveryRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = returnFunc(ctx, deliveryRequestID, failureCode, failureMessage)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeliveryRequestRepository_MarkFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkFailed'
type MockDeliveryRequestRepository_MarkFailed_Call struct {
	*mock.Call
}

// MarkFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - deliveryRequestID uuid.UUID
//   - failureCode string
//   - failureMessage string
func (_e *MockDeliveryRequestRepository_Expecter) MarkFailed(ctx interface{}, deliveryRequestID interface{}, failureCode interface{}, failureMessage interface{}) *MockDeliveryRequestRepository_MarkFailed_Call {
	return &MockDeliveryRequestRepository_MarkFailed_Call{Call: _e.mock.On("MarkFailed", ctx, deliveryRequestID, failureCode, failureMessage)}
}

func (_c *MockDeliveryRequestRepository_MarkFailed_Call) Run(run func(ctx context.Context, deliveryRequestID uuid.UUID, failureCode string, failureMessage string)) *MockDeliveryRequestRepository_MarkFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockDeliveryRequestRepository_MarkFailed_Call) Return(deliveryRequest domain.DeliveryRequest, err error) *MockDeliveryRequestRepository_MarkFailed_Call {
	_c.Call.Return(deliveryRequest, err)
	return _c
}

func (_c *MockDeliveryRequestRepository_MarkFailed_Call) RunAndReturn(run func(ctx context.Context, deliveryRequestID uuid.UUID, failureCode string, failureMessage string) (domain.DeliveryRequest, error)) *MockDeliveryRequestRepository_MarkFailed_Call {
	_c.Call.Return(run)
	return _c
}

// MarkSent provides a mock function for the type MockDeliveryRequestRepository
func (_mock *MockDeliveryRequestRepository) MarkSent(ctx context.Context, deliveryRequestID uuid.UUID) (domain.DeliveryRequest, error) {
	ret := _mock.Called(ctx, deliveryRequestID)

	if len(ret) == 0 {
		panic("no return value specified for MarkSent")
	}

	var r0 domain.DeliveryRequest
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.DeliveryRequest, error)); ok {
		return returnFunc(ctx, deliveryRequestID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.DeliveryRequest); ok {
		r0 = returnFunc(ctx, deliveryRequestID)
	} else {
		r0 = ret.Get(0).(domain.DeliveryRequest)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, deliveryRequestID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDeliveryRequestRepository_MarkSent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkSent'
type MockDeliveryRequestRepository_MarkSent_Call struct {
	*mock.Call
}

// MarkSent is a helper method to define mock.On call
//   - ctx context.Context
//   - deliveryRequestID uuid.UUID
func (_e *MockDeliveryRequestRepository_Expecter) MarkSent(ctx interface{}, deliveryRequestID interface{}) *MockDeliveryRequestRepository_MarkSent_Call {
	return &MockDeliveryRequestRepository_MarkSent_Call{Call: _e.mock.On("MarkSent", ctx, deliveryRequestID)}
}

func (_c *MockDeliveryRequestRepository_MarkSent_Call) Run(run func(ctx context.Context, deliveryRequestID uuid.UUID)) *MockDeliveryRequestRepository_MarkSent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDeliveryRequestRepository_MarkSent_Call) Return(deliveryRequest domain.DeliveryRequest, err error) *MockDeliveryRequestRepository_MarkSent_Call {
	_c.Call.Return(deliveryRequest, err)
	return _c
}

func (_c *MockDeliveryRequestRepository_MarkSent_Call) RunAndReturn(run func(ctx context.Context, deliveryRequestID uuid.UUID) (domain.DeliveryRequest, error)) *MockDeliveryRequestRepository_MarkSent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher {
	mock := &MockEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

type MockEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher) EXPECT() *MockEventPublisher_Expecter {
	return &MockEventPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockEventPublisher
func (_mock *MockEventPublisher) Publish(ctx context.Context, event domain.DomainEvent) error {
	ret := _mock.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.DomainEvent) error); ok {
		r0 = returnFunc(ctx, event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockEventPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.DomainEvent
func (_e *MockEventPublisher_Expecter) Publish(ctx interface{}, event interface{}) *MockEventPublisher_Publish_Call {
	return &MockEventPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, event)}
}

func (_c *MockEventPublisher_Publish_Call) Run(run func(ctx context.Context, event domain.DomainEvent)) *MockEventPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.DomainEvent
		if args[1] != nil {
			arg1 = args[1].(domain.DomainEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventPublisher_Publish_Call) Return(err error) *MockEventPublisher_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventPublisher_Publish_Call) RunAndReturn(run func(ctx context.Context, event domain.DomainEvent) error) *MockEventPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}
