// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package dto

import (
	"context"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for CreateProductRequestStatus.
const (
	CreateProductRequestStatusArchived  CreateProductRequestStatus = "archived"
	CreateProductRequestStatusDraft     CreateProductRequestStatus = "draft"
	CreateProductRequestStatusPublished CreateProductRequestStatus = "published"
)

// Defines values for ProductStatus.
const (
	ProductStatusArchived  ProductStatus = "archived"
	ProductStatusDraft     ProductStatus = "draft"
	ProductStatusPublished ProductStatus = "published"
)

// Defines values for StockSummaryStatus.
const (
	InStock    StockSummaryStatus = "in_stock"
	OutOfStock StockSummaryStatus = "out_of_stock"
)

// Defines values for UpdateProductRequestStatus.
const (
	Archived  UpdateProductRequestStatus = "archived"
	Draft     UpdateProductRequestStatus = "draft"
	Published UpdateProductRequestStatus = "published"
)

// CreateProductRequest defines model for CreateProductRequest.
type CreateProductRequest struct {
	CategoryId      *openapi_types.UUID         `json:"categoryId,omitempty"`
	CurrencyCode    string                      `json:"currencyCode"`
	Description     *string                     `json:"description,omitempty"`
	InitialQuantity int                         `json:"initialQuantity"`
	Name            string                      `json:"name"`
	Price           int                         `json:"price"`
	Sku             string                      `json:"sku"`
	Status          *CreateProductRequestStatus `json:"status,omitempty"`
}

// CreateProductRequestStatus defines model for CreateProductRequest.Status.
type CreateProductRequestStatus string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code          string  `json:"code"`
	CorrelationId *string `json:"correlationId,omitempty"`
	Message       string  `json:"message"`
}

// Product defines model for Product.
type Product struct {
	CategoryId  *openapi_types.UUID `json:"categoryId,omitempty"`
	Currency    string              `json:"currency"`
	Description *string             `json:"description,omitempty"`
	Name        string              `json:"name"`
	Price       int                 `json:"price"`
	ProductId   string              `json:"productId"`
	Sku         string              `json:"sku"`
	Status      ProductStatus       `json:"status"`
}

// ProductStatus defines model for Product.Status.
type ProductStatus string

// ProductListResponse defines model for ProductListResponse.
type ProductListResponse struct {
	Items []Product `json:"items"`
}

// ProductWriteResponse defines model for ProductWriteResponse.
type ProductWriteResponse struct {
	Product Product      `json:"product"`
	Stock   StockSummary `json:"stock"`
}

// StockSummary defines model for StockSummary.
type StockSummary struct {
	Available int                `json:"available"`
	Quantity  int                `json:"quantity"`
	Reserved  int                `json:"reserved"`
	Status    StockSummaryStatus `json:"status"`
}

// StockSummaryStatus defines model for StockSummary.Status.
type StockSummaryStatus string

// UpdateProductRequest defines model for UpdateProductRequest.
type UpdateProductRequest struct {
	CategoryId  *openapi_types.UUID         `json:"categoryId,omitempty"`
	Description *string                     `json:"description,omitempty"`
	Name        *string                     `json:"name,omitempty"`
	Price       *int                        `json:"price,omitempty"`
	Sku         *string                     `json:"sku,omitempty"`
	Status      *UpdateProductRequestStatus `json:"status,omitempty"`
}

// UpdateProductRequestStatus defines model for UpdateProductRequest.Status.
type UpdateProductRequestStatus string

// ProductId defines model for ProductId.
type ProductId = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// CreateProductJSONRequestBody defines body for CreateProduct for application/json ContentType.
type CreateProductJSONRequestBody = CreateProductRequest

// UpdateProductByIdJSONRequestBody defines body for UpdateProductById for application/json ContentType.
type UpdateProductByIdJSONRequestBody = UpdateProductRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List published products
	// (GET /v1/products)
	ListPublishedProducts(w http.ResponseWriter, r *http.Request)
	// Create product
	// (POST /v1/products)
	CreateProduct(w http.ResponseWriter, r *http.Request)
	// Archive product by id (soft delete)
	// (DELETE /v1/products/{productId})
	DeleteProductById(w http.ResponseWriter, r *http.Request, productId ProductId)
	// Get product by id
	// (GET /v1/products/{productId})
	GetProductById(w http.ResponseWriter, r *http.Request, productId ProductId)
	// Update product by id
	// (PATCH /v1/products/{productId})
	UpdateProductById(w http.ResponseWriter, r *http.Request, productId ProductId)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List published products
// (GET /v1/products)
func (_ Unimplemented) ListPublishedProducts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create product
// (POST /v1/products)
func (_ Unimplemented) CreateProduct(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Archive product by id (soft delete)
// (DELETE /v1/products/{productId})
func (_ Unimplemented) DeleteProductById(w http.ResponseWriter, r *http.Request, productId ProductId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get product by id
// (GET /v1/products/{productId})
func (_ Unimplemented) GetProductById(w http.ResponseWriter, r *http.Request, productId ProductId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update product by id
// (PATCH /v1/products/{productId})
func (_ Unimplemented) UpdateProductById(w http.ResponseWriter, r *http.Request, productId ProductId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListPublishedProducts operation middleware
func (siw *ServerInterfaceWrapper) ListPublishedProducts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPublishedProducts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProduct operation middleware
func (siw *ServerInterfaceWrapper) CreateProduct(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProduct(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProductById operation middleware
func (siw *ServerInterfaceWrapper) DeleteProductById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", chi.URLParam(r, "productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProductById(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProductById operation middleware
func (siw *ServerInterfaceWrapper) GetProductById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", chi.URLParam(r, "productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProductById(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProductById operation middleware
func (siw *ServerInterfaceWrapper) UpdateProductById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "productId" -------------
	var productId ProductId

	err = runtime.BindStyledParameterWithOptions("simple", "productId", chi.URLParam(r, "productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProductById(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/products", wrapper.ListPublishedProducts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/products", wrapper.CreateProduct)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/v1/products/{productId}", wrapper.DeleteProductById)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/products/{productId}", wrapper.GetProductById)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/v1/products/{productId}", wrapper.UpdateProductById)
	})

	return r
}
