// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package outboundmocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/shrtyk/e-commerce-platform/internal/order-svc/internal/core/ports/outbound"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCheckoutSnapshotRepository creates a new instance of MockCheckoutSnapshotRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckoutSnapshotRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckoutSnapshotRepository {
	mock := &MockCheckoutSnapshotRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCheckoutSnapshotRepository is an autogenerated mock type for the CheckoutSnapshotRepository type
type MockCheckoutSnapshotRepository struct {
	mock.Mock
}

type MockCheckoutSnapshotRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCheckoutSnapshotRepository) EXPECT() *MockCheckoutSnapshotRepository_Expecter {
	return &MockCheckoutSnapshotRepository_Expecter{mock: &_m.Mock}
}

// GetCheckoutSnapshot provides a mock function for the type MockCheckoutSnapshotRepository
func (_mock *MockCheckoutSnapshotRepository) GetCheckoutSnapshot(ctx context.Context, userID uuid.UUID) (outbound.CheckoutSnapshot, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCheckoutSnapshot")
	}

	var r0 outbound.CheckoutSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (outbound.CheckoutSnapshot, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) outbound.CheckoutSnapshot); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(outbound.CheckoutSnapshot)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCheckoutSnapshotRepository_GetCheckoutSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCheckoutSnapshot'
type MockCheckoutSnapshotRepository_GetCheckoutSnapshot_Call struct {
	*mock.Call
}

// GetCheckoutSnapshot is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockCheckoutSnapshotRepository_Expecter) GetCheckoutSnapshot(ctx interface{}, userID interface{}) *MockCheckoutSnapshotRepository_GetCheckoutSnapshot_Call {
	return &MockCheckoutSnapshotRepository_GetCheckoutSnapshot_Call{Call: _e.mock.On("GetCheckoutSnapshot", ctx, userID)}
}

func (_c *MockCheckoutSnapshotRepository_GetCheckoutSnapshot_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockCheckoutSnapshotRepository_GetCheckoutSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCheckoutSnapshotRepository_GetCheckoutSnapshot_Call) Return(checkoutSnapshot outbound.CheckoutSnapshot, err error) *MockCheckoutSnapshotRepository_GetCheckoutSnapshot_Call {
	_c.Call.Return(checkoutSnapshot, err)
	return _c
}

func (_c *MockCheckoutSnapshotRepository_GetCheckoutSnapshot_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (outbound.CheckoutSnapshot, error)) *MockCheckoutSnapshotRepository_GetCheckoutSnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStockReservationService creates a new instance of MockStockReservationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStockReservationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStockReservationService {
	mock := &MockStockReservationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStockReservationService is an autogenerated mock type for the StockReservationService type
type MockStockReservationService struct {
	mock.Mock
}

type MockStockReservationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStockReservationService) EXPECT() *MockStockReservationService_Expecter {
	return &MockStockReservationService_Expecter{mock: &_m.Mock}
}

// ReserveStock provides a mock function for the type MockStockReservationService
func (_mock *MockStockReservationService) ReserveStock(ctx context.Context, input outbound.ReserveStockInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ReserveStock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbound.ReserveStockInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStockReservationService_ReserveStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReserveStock'
type MockStockReservationService_ReserveStock_Call struct {
	*mock.Call
}

// ReserveStock is a helper method to define mock.On call
//   - ctx context.Context
//   - input outbound.ReserveStockInput
func (_e *MockStockReservationService_Expecter) ReserveStock(ctx interface{}, input interface{}) *MockStockReservationService_ReserveStock_Call {
	return &MockStockReservationService_ReserveStock_Call{Call: _e.mock.On("ReserveStock", ctx, input)}
}

func (_c *MockStockReservationService_ReserveStock_Call) Run(run func(ctx context.Context, input outbound.ReserveStockInput)) *MockStockReservationService_ReserveStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 outbound.ReserveStockInput
		if args[1] != nil {
			arg1 = args[1].(outbound.ReserveStockInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStockReservationService_ReserveStock_Call) Return(err error) *MockStockReservationService_ReserveStock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStockReservationService_ReserveStock_Call) RunAndReturn(run func(ctx context.Context, input outbound.ReserveStockInput) error) *MockStockReservationService_ReserveStock_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStockReleaseService creates a new instance of MockStockReleaseService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStockReleaseService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStockReleaseService {
	mock := &MockStockReleaseService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStockReleaseService is an autogenerated mock type for the StockReleaseService type
type MockStockReleaseService struct {
	mock.Mock
}

type MockStockReleaseService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStockReleaseService) EXPECT() *MockStockReleaseService_Expecter {
	return &MockStockReleaseService_Expecter{mock: &_m.Mock}
}

// ReleaseStock provides a mock function for the type MockStockReleaseService
func (_mock *MockStockReleaseService) ReleaseStock(ctx context.Context, input outbound.ReleaseStockInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseStock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbound.ReleaseStockInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStockReleaseService_ReleaseStock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReleaseStock'
type MockStockReleaseService_ReleaseStock_Call struct {
	*mock.Call
}

// ReleaseStock is a helper method to define mock.On call
//   - ctx context.Context
//   - input outbound.ReleaseStockInput
func (_e *MockStockReleaseService_Expecter) ReleaseStock(ctx interface{}, input interface{}) *MockStockReleaseService_ReleaseStock_Call {
	return &MockStockReleaseService_ReleaseStock_Call{Call: _e.mock.On("ReleaseStock", ctx, input)}
}

func (_c *MockStockReleaseService_ReleaseStock_Call) Run(run func(ctx context.Context, input outbound.ReleaseStockInput)) *MockStockReleaseService_ReleaseStock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 outbound.ReleaseStockInput
		if args[1] != nil {
			arg1 = args[1].(outbound.ReleaseStockInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStockReleaseService_ReleaseStock_Call) Return(err error) *MockStockReleaseService_ReleaseStock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStockReleaseService_ReleaseStock_Call) RunAndReturn(run func(ctx context.Context, input outbound.ReleaseStockInput) error) *MockStockReleaseService_ReleaseStock_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCheckoutPaymentService creates a new instance of MockCheckoutPaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckoutPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckoutPaymentService {
	mock := &MockCheckoutPaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCheckoutPaymentService is an autogenerated mock type for the CheckoutPaymentService type
type MockCheckoutPaymentService struct {
	mock.Mock
}

type MockCheckoutPaymentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCheckoutPaymentService) EXPECT() *MockCheckoutPaymentService_Expecter {
	return &MockCheckoutPaymentService_Expecter{mock: &_m.Mock}
}

// InitiatePayment provides a mock function for the type MockCheckoutPaymentService
func (_mock *MockCheckoutPaymentService) InitiatePayment(ctx context.Context, input outbound.InitiatePaymentInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for InitiatePayment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbound.InitiatePaymentInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCheckoutPaymentService_InitiatePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitiatePayment'
type MockCheckoutPaymentService_InitiatePayment_Call struct {
	*mock.Call
}

// InitiatePayment is a helper method to define mock.On call
//   - ctx context.Context
//   - input outbound.InitiatePaymentInput
func (_e *MockCheckoutPaymentService_Expecter) InitiatePayment(ctx interface{}, input interface{}) *MockCheckoutPaymentService_InitiatePayment_Call {
	return &MockCheckoutPaymentService_InitiatePayment_Call{Call: _e.mock.On("InitiatePayment", ctx, input)}
}

func (_c *MockCheckoutPaymentService_InitiatePayment_Call) Run(run func(ctx context.Context, input outbound.InitiatePaymentInput)) *MockCheckoutPaymentService_InitiatePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 outbound.InitiatePaymentInput
		if args[1] != nil {
			arg1 = args[1].(outbound.InitiatePaymentInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCheckoutPaymentService_InitiatePayment_Call) Return(err error) *MockCheckoutPaymentService_InitiatePayment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCheckoutPaymentService_InitiatePayment_Call) RunAndReturn(run func(ctx context.Context, input outbound.InitiatePaymentInput) error) *MockCheckoutPaymentService_InitiatePayment_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCheckoutIdempotencyGuard creates a new instance of MockCheckoutIdempotencyGuard. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckoutIdempotencyGuard(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckoutIdempotencyGuard {
	mock := &MockCheckoutIdempotencyGuard{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCheckoutIdempotencyGuard is an autogenerated mock type for the CheckoutIdempotencyGuard type
type MockCheckoutIdempotencyGuard struct {
	mock.Mock
}

type MockCheckoutIdempotencyGuard_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCheckoutIdempotencyGuard) EXPECT() *MockCheckoutIdempotencyGuard_Expecter {
	return &MockCheckoutIdempotencyGuard_Expecter{mock: &_m.Mock}
}

// ValidateCheckoutIdempotency provides a mock function for the type MockCheckoutIdempotencyGuard
func (_mock *MockCheckoutIdempotencyGuard) ValidateCheckoutIdempotency(ctx context.Context, input outbound.ValidateCheckoutIdempotencyInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCheckoutIdempotency")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbound.ValidateCheckoutIdempotencyInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCheckoutIdempotencyGuard_ValidateCheckoutIdempotency_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateCheckoutIdempotency'
type MockCheckoutIdempotencyGuard_ValidateCheckoutIdempotency_Call struct {
	*mock.Call
}

// ValidateCheckoutIdempotency is a helper method to define mock.On call
//   - ctx context.Context
//   - input outbound.ValidateCheckoutIdempotencyInput
func (_e *MockCheckoutIdempotencyGuard_Expecter) ValidateCheckoutIdempotency(ctx interface{}, input interface{}) *MockCheckoutIdempotencyGuard_ValidateCheckoutIdempotency_Call {
	return &MockCheckoutIdempotencyGuard_ValidateCheckoutIdempotency_Call{Call: _e.mock.On("ValidateCheckoutIdempotency", ctx, input)}
}

func (_c *MockCheckoutIdempotencyGuard_ValidateCheckoutIdempotency_Call) Run(run func(ctx context.Context, input outbound.ValidateCheckoutIdempotencyInput)) *MockCheckoutIdempotencyGuard_ValidateCheckoutIdempotency_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 outbound.ValidateCheckoutIdempotencyInput
		if args[1] != nil {
			arg1 = args[1].(outbound.ValidateCheckoutIdempotencyInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCheckoutIdempotencyGuard_ValidateCheckoutIdempotency_Call) Return(err error) *MockCheckoutIdempotencyGuard_ValidateCheckoutIdempotency_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCheckoutIdempotencyGuard_ValidateCheckoutIdempotency_Call) RunAndReturn(run func(ctx context.Context, input outbound.ValidateCheckoutIdempotencyInput) error) *MockCheckoutIdempotencyGuard_ValidateCheckoutIdempotency_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// AppendStatusHistory provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) AppendStatusHistory(ctx context.Context, orderID uuid.UUID, fromStatus *outbound.OrderStatus, toStatus outbound.OrderStatus, reasonCode *string) (outbound.OrderStatusHistory, error) {
	ret := _mock.Called(ctx, orderID, fromStatus, toStatus, reasonCode)

	if len(ret) == 0 {
		panic("no return value specified for AppendStatusHistory")
	}

	var r0 outbound.OrderStatusHistory
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *outbound.OrderStatus, outbound.OrderStatus, *string) (outbound.OrderStatusHistory, error)); ok {
		return returnFunc(ctx, orderID, fromStatus, toStatus, reasonCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *outbound.OrderStatus, outbound.OrderStatus, *string) outbound.OrderStatusHistory); ok {
		r0 = returnFunc(ctx, orderID, fromStatus, toStatus, reasonCode)
	} else {
		r0 = ret.Get(0).(outbound.OrderStatusHistory)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *outbound.OrderStatus, outbound.OrderStatus, *string) error); ok {
		r1 = returnFunc(ctx, orderID, fromStatus, toStatus, reasonCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_AppendStatusHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AppendStatusHistory'
type MockOrderRepository_AppendStatusHistory_Call struct {
	*mock.Call
}

// AppendStatusHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
//   - fromStatus *outbound.OrderStatus
//   - toStatus outbound.OrderStatus
//   - reasonCode *string
func (_e *MockOrderRepository_Expecter) AppendStatusHistory(ctx interface{}, orderID interface{}, fromStatus interface{}, toStatus interface{}, reasonCode interface{}) *MockOrderRepository_AppendStatusHistory_Call {
	return &MockOrderRepository_AppendStatusHistory_Call{Call: _e.mock.On("AppendStatusHistory", ctx, orderID, fromStatus, toStatus, reasonCode)}
}

func (_c *MockOrderRepository_AppendStatusHistory_Call) Run(run func(ctx context.Context, orderID uuid.UUID, fromStatus *outbound.OrderStatus, toStatus outbound.OrderStatus, reasonCode *string)) *MockOrderRepository_AppendStatusHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *outbound.OrderStatus
		if args[2] != nil {
			arg2 = args[2].(*outbound.OrderStatus)
		}
		var arg3 outbound.OrderStatus
		if args[3] != nil {
			arg3 = args[3].(outbound.OrderStatus)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockOrderRepository_AppendStatusHistory_Call) Return(orderStatusHistory outbound.OrderStatusHistory, err error) *MockOrderRepository_AppendStatusHistory_Call {
	_c.Call.Return(orderStatusHistory, err)
	return _c
}

func (_c *MockOrderRepository_AppendStatusHistory_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID, fromStatus *outbound.OrderStatus, toStatus outbound.OrderStatus, reasonCode *string) (outbound.OrderStatusHistory, error)) *MockOrderRepository_AppendStatusHistory_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithItems provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) CreateWithItems(ctx context.Context, input outbound.CreateOrderInput) (outbound.Order, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateWithItems")
	}

	var r0 outbound.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbound.CreateOrderInput) (outbound.Order, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbound.CreateOrderInput) outbound.Order); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Get(0).(outbound.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, outbound.CreateOrderInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_CreateWithItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithItems'
type MockOrderRepository_CreateWithItems_Call struct {
	*mock.Call
}

// CreateWithItems is a helper method to define mock.On call
//   - ctx context.Context
//   - input outbound.CreateOrderInput
func (_e *MockOrderRepository_Expecter) CreateWithItems(ctx interface{}, input interface{}) *MockOrderRepository_CreateWithItems_Call {
	return &MockOrderRepository_CreateWithItems_Call{Call: _e.mock.On("CreateWithItems", ctx, input)}
}

func (_c *MockOrderRepository_CreateWithItems_Call) Run(run func(ctx context.Context, input outbound.CreateOrderInput)) *MockOrderRepository_CreateWithItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 outbound.CreateOrderInput
		if args[1] != nil {
			arg1 = args[1].(outbound.CreateOrderInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_CreateWithItems_Call) Return(order outbound.Order, err error) *MockOrderRepository_CreateWithItems_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepository_CreateWithItems_Call) RunAndReturn(run func(ctx context.Context, input outbound.CreateOrderInput) (outbound.Order, error)) *MockOrderRepository_CreateWithItems_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) GetByID(ctx context.Context, orderID uuid.UUID) (outbound.Order, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 outbound.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (outbound.Order, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) outbound.Order); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Get(0).(outbound.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockOrderRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderRepository_Expecter) GetByID(ctx interface{}, orderID interface{}) *MockOrderRepository_GetByID_Call {
	return &MockOrderRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, orderID)}
}

func (_c *MockOrderRepository_GetByID_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_GetByID_Call) Return(order outbound.Order, err error) *MockOrderRepository_GetByID_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (outbound.Order, error)) *MockOrderRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserIDAndIdempotencyKey provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) GetByUserIDAndIdempotencyKey(ctx context.Context, userID uuid.UUID, idempotencyKey string) (outbound.Order, error) {
	ret := _mock.Called(ctx, userID, idempotencyKey)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserIDAndIdempotencyKey")
	}

	var r0 outbound.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (outbound.Order, error)); ok {
		return returnFunc(ctx, userID, idempotencyKey)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) outbound.Order); ok {
		r0 = returnFunc(ctx, userID, idempotencyKey)
	} else {
		r0 = ret.Get(0).(outbound.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, userID, idempotencyKey)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_GetByUserIDAndIdempotencyKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserIDAndIdempotencyKey'
type MockOrderRepository_GetByUserIDAndIdempotencyKey_Call struct {
	*mock.Call
}

// GetByUserIDAndIdempotencyKey is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - idempotencyKey string
func (_e *MockOrderRepository_Expecter) GetByUserIDAndIdempotencyKey(ctx interface{}, userID interface{}, idempotencyKey interface{}) *MockOrderRepository_GetByUserIDAndIdempotencyKey_Call {
	return &MockOrderRepository_GetByUserIDAndIdempotencyKey_Call{Call: _e.mock.On("GetByUserIDAndIdempotencyKey", ctx, userID, idempotencyKey)}
}

func (_c *MockOrderRepository_GetByUserIDAndIdempotencyKey_Call) Run(run func(ctx context.Context, userID uuid.UUID, idempotencyKey string)) *MockOrderRepository_GetByUserIDAndIdempotencyKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderRepository_GetByUserIDAndIdempotencyKey_Call) Return(order outbound.Order, err error) *MockOrderRepository_GetByUserIDAndIdempotencyKey_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepository_GetByUserIDAndIdempotencyKey_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, idempotencyKey string) (outbound.Order, error)) *MockOrderRepository_GetByUserIDAndIdempotencyKey_Call {
	_c.Call.Return(run)
	return _c
}

// TransitionStatus provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) TransitionStatus(ctx context.Context, orderID uuid.UUID, fromStatus outbound.OrderStatus, toStatus outbound.OrderStatus) (outbound.Order, error) {
	ret := _mock.Called(ctx, orderID, fromStatus, toStatus)

	if len(ret) == 0 {
		panic("no return value specified for TransitionStatus")
	}

	var r0 outbound.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, outbound.OrderStatus, outbound.OrderStatus) (outbound.Order, error)); ok {
		return returnFunc(ctx, orderID, fromStatus, toStatus)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, outbound.OrderStatus, outbound.OrderStatus) outbound.Order); ok {
		r0 = returnFunc(ctx, orderID, fromStatus, toStatus)
	} else {
		r0 = ret.Get(0).(outbound.Order)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, outbound.OrderStatus, outbound.OrderStatus) error); ok {
		r1 = returnFunc(ctx, orderID, fromStatus, toStatus)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_TransitionStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransitionStatus'
type MockOrderRepository_TransitionStatus_Call struct {
	*mock.Call
}

// TransitionStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
//   - fromStatus outbound.OrderStatus
//   - toStatus outbound.OrderStatus
func (_e *MockOrderRepository_Expecter) TransitionStatus(ctx interface{}, orderID interface{}, fromStatus interface{}, toStatus interface{}) *MockOrderRepository_TransitionStatus_Call {
	return &MockOrderRepository_TransitionStatus_Call{Call: _e.mock.On("TransitionStatus", ctx, orderID, fromStatus, toStatus)}
}

func (_c *MockOrderRepository_TransitionStatus_Call) Run(run func(ctx context.Context, orderID uuid.UUID, fromStatus outbound.OrderStatus, toStatus outbound.OrderStatus)) *MockOrderRepository_TransitionStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 outbound.OrderStatus
		if args[2] != nil {
			arg2 = args[2].(outbound.OrderStatus)
		}
		var arg3 outbound.OrderStatus
		if args[3] != nil {
			arg3 = args[3].(outbound.OrderStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockOrderRepository_TransitionStatus_Call) Return(order outbound.Order, err error) *MockOrderRepository_TransitionStatus_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepository_TransitionStatus_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID, fromStatus outbound.OrderStatus, toStatus outbound.OrderStatus) (outbound.Order, error)) *MockOrderRepository_TransitionStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderSagaStateRepository creates a new instance of MockOrderSagaStateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderSagaStateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderSagaStateRepository {
	mock := &MockOrderSagaStateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderSagaStateRepository is an autogenerated mock type for the OrderSagaStateRepository type
type MockOrderSagaStateRepository struct {
	mock.Mock
}

type MockOrderSagaStateRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderSagaStateRepository) EXPECT() *MockOrderSagaStateRepository_Expecter {
	return &MockOrderSagaStateRepository_Expecter{mock: &_m.Mock}
}

// ClearLastErrorCode provides a mock function for the type MockOrderSagaStateRepository
func (_mock *MockOrderSagaStateRepository) ClearLastErrorCode(ctx context.Context, orderID uuid.UUID) (outbound.SagaState, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for ClearLastErrorCode")
	}

	var r0 outbound.SagaState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (outbound.SagaState, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) outbound.SagaState); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Get(0).(outbound.SagaState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderSagaStateRepository_ClearLastErrorCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearLastErrorCode'
type MockOrderSagaStateRepository_ClearLastErrorCode_Call struct {
	*mock.Call
}

// ClearLastErrorCode is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderSagaStateRepository_Expecter) ClearLastErrorCode(ctx interface{}, orderID interface{}) *MockOrderSagaStateRepository_ClearLastErrorCode_Call {
	return &MockOrderSagaStateRepository_ClearLastErrorCode_Call{Call: _e.mock.On("ClearLastErrorCode", ctx, orderID)}
}

func (_c *MockOrderSagaStateRepository_ClearLastErrorCode_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderSagaStateRepository_ClearLastErrorCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderSagaStateRepository_ClearLastErrorCode_Call) Return(sagaState outbound.SagaState, err error) *MockOrderSagaStateRepository_ClearLastErrorCode_Call {
	_c.Call.Return(sagaState, err)
	return _c
}

func (_c *MockOrderSagaStateRepository_ClearLastErrorCode_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (outbound.SagaState, error)) *MockOrderSagaStateRepository_ClearLastErrorCode_Call {
	_c.Call.Return(run)
	return _c
}

// SetLastErrorCode provides a mock function for the type MockOrderSagaStateRepository
func (_mock *MockOrderSagaStateRepository) SetLastErrorCode(ctx context.Context, orderID uuid.UUID, lastErrorCode string) (outbound.SagaState, error) {
	ret := _mock.Called(ctx, orderID, lastErrorCode)

	if len(ret) == 0 {
		panic("no return value specified for SetLastErrorCode")
	}

	var r0 outbound.SagaState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (outbound.SagaState, error)); ok {
		return returnFunc(ctx, orderID, lastErrorCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) outbound.SagaState); ok {
		r0 = returnFunc(ctx, orderID, lastErrorCode)
	} else {
		r0 = ret.Get(0).(outbound.SagaState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, orderID, lastErrorCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderSagaStateRepository_SetLastErrorCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLastErrorCode'
type MockOrderSagaStateRepository_SetLastErrorCode_Call struct {
	*mock.Call
}

// SetLastErrorCode is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
//   - lastErrorCode string
func (_e *MockOrderSagaStateRepository_Expecter) SetLastErrorCode(ctx interface{}, orderID interface{}, lastErrorCode interface{}) *MockOrderSagaStateRepository_SetLastErrorCode_Call {
	return &MockOrderSagaStateRepository_SetLastErrorCode_Call{Call: _e.mock.On("SetLastErrorCode", ctx, orderID, lastErrorCode)}
}

func (_c *MockOrderSagaStateRepository_SetLastErrorCode_Call) Run(run func(ctx context.Context, orderID uuid.UUID, lastErrorCode string)) *MockOrderSagaStateRepository_SetLastErrorCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderSagaStateRepository_SetLastErrorCode_Call) Return(sagaState outbound.SagaState, err error) *MockOrderSagaStateRepository_SetLastErrorCode_Call {
	_c.Call.Return(sagaState, err)
	return _c
}

func (_c *MockOrderSagaStateRepository_SetLastErrorCode_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID, lastErrorCode string) (outbound.SagaState, error)) *MockOrderSagaStateRepository_SetLastErrorCode_Call {
	_c.Call.Return(run)
	return _c
}

// TransitionPaymentStageToFailed provides a mock function for the type MockOrderSagaStateRepository
func (_mock *MockOrderSagaStateRepository) TransitionPaymentStageToFailed(ctx context.Context, orderID uuid.UUID) (outbound.SagaState, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for TransitionPaymentStageToFailed")
	}

	var r0 outbound.SagaState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (outbound.SagaState, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) outbound.SagaState); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Get(0).(outbound.SagaState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderSagaStateRepository_TransitionPaymentStageToFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransitionPaymentStageToFailed'
type MockOrderSagaStateRepository_TransitionPaymentStageToFailed_Call struct {
	*mock.Call
}

// TransitionPaymentStageToFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderSagaStateRepository_Expecter) TransitionPaymentStageToFailed(ctx interface{}, orderID interface{}) *MockOrderSagaStateRepository_TransitionPaymentStageToFailed_Call {
	return &MockOrderSagaStateRepository_TransitionPaymentStageToFailed_Call{Call: _e.mock.On("TransitionPaymentStageToFailed", ctx, orderID)}
}

func (_c *MockOrderSagaStateRepository_TransitionPaymentStageToFailed_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderSagaStateRepository_TransitionPaymentStageToFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderSagaStateRepository_TransitionPaymentStageToFailed_Call) Return(sagaState outbound.SagaState, err error) *MockOrderSagaStateRepository_TransitionPaymentStageToFailed_Call {
	_c.Call.Return(sagaState, err)
	return _c
}

func (_c *MockOrderSagaStateRepository_TransitionPaymentStageToFailed_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (outbound.SagaState, error)) *MockOrderSagaStateRepository_TransitionPaymentStageToFailed_Call {
	_c.Call.Return(run)
	return _c
}

// TransitionPaymentStageToRequested provides a mock function for the type MockOrderSagaStateRepository
func (_mock *MockOrderSagaStateRepository) TransitionPaymentStageToRequested(ctx context.Context, orderID uuid.UUID) (outbound.SagaState, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for TransitionPaymentStageToRequested")
	}

	var r0 outbound.SagaState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (outbound.SagaState, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) outbound.SagaState); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Get(0).(outbound.SagaState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderSagaStateRepository_TransitionPaymentStageToRequested_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransitionPaymentStageToRequested'
type MockOrderSagaStateRepository_TransitionPaymentStageToRequested_Call struct {
	*mock.Call
}

// TransitionPaymentStageToRequested is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderSagaStateRepository_Expecter) TransitionPaymentStageToRequested(ctx interface{}, orderID interface{}) *MockOrderSagaStateRepository_TransitionPaymentStageToRequested_Call {
	return &MockOrderSagaStateRepository_TransitionPaymentStageToRequested_Call{Call: _e.mock.On("TransitionPaymentStageToRequested", ctx, orderID)}
}

func (_c *MockOrderSagaStateRepository_TransitionPaymentStageToRequested_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderSagaStateRepository_TransitionPaymentStageToRequested_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderSagaStateRepository_TransitionPaymentStageToRequested_Call) Return(sagaState outbound.SagaState, err error) *MockOrderSagaStateRepository_TransitionPaymentStageToRequested_Call {
	_c.Call.Return(sagaState, err)
	return _c
}

func (_c *MockOrderSagaStateRepository_TransitionPaymentStageToRequested_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (outbound.SagaState, error)) *MockOrderSagaStateRepository_TransitionPaymentStageToRequested_Call {
	_c.Call.Return(run)
	return _c
}

// TransitionPaymentStageToSucceeded provides a mock function for the type MockOrderSagaStateRepository
func (_mock *MockOrderSagaStateRepository) TransitionPaymentStageToSucceeded(ctx context.Context, orderID uuid.UUID) (outbound.SagaState, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for TransitionPaymentStageToSucceeded")
	}

	var r0 outbound.SagaState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (outbound.SagaState, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) outbound.SagaState); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Get(0).(outbound.SagaState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderSagaStateRepository_TransitionPaymentStageToSucceeded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransitionPaymentStageToSucceeded'
type MockOrderSagaStateRepository_TransitionPaymentStageToSucceeded_Call struct {
	*mock.Call
}

// TransitionPaymentStageToSucceeded is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderSagaStateRepository_Expecter) TransitionPaymentStageToSucceeded(ctx interface{}, orderID interface{}) *MockOrderSagaStateRepository_TransitionPaymentStageToSucceeded_Call {
	return &MockOrderSagaStateRepository_TransitionPaymentStageToSucceeded_Call{Call: _e.mock.On("TransitionPaymentStageToSucceeded", ctx, orderID)}
}

func (_c *MockOrderSagaStateRepository_TransitionPaymentStageToSucceeded_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderSagaStateRepository_TransitionPaymentStageToSucceeded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderSagaStateRepository_TransitionPaymentStageToSucceeded_Call) Return(sagaState outbound.SagaState, err error) *MockOrderSagaStateRepository_TransitionPaymentStageToSucceeded_Call {
	_c.Call.Return(sagaState, err)
	return _c
}

func (_c *MockOrderSagaStateRepository_TransitionPaymentStageToSucceeded_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (outbound.SagaState, error)) *MockOrderSagaStateRepository_TransitionPaymentStageToSucceeded_Call {
	_c.Call.Return(run)
	return _c
}

// TransitionStockStageToFailed provides a mock function for the type MockOrderSagaStateRepository
func (_mock *MockOrderSagaStateRepository) TransitionStockStageToFailed(ctx context.Context, orderID uuid.UUID) (outbound.SagaState, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for TransitionStockStageToFailed")
	}

	var r0 outbound.SagaState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (outbound.SagaState, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) outbound.SagaState); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Get(0).(outbound.SagaState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderSagaStateRepository_TransitionStockStageToFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransitionStockStageToFailed'
type MockOrderSagaStateRepository_TransitionStockStageToFailed_Call struct {
	*mock.Call
}

// TransitionStockStageToFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderSagaStateRepository_Expecter) TransitionStockStageToFailed(ctx interface{}, orderID interface{}) *MockOrderSagaStateRepository_TransitionStockStageToFailed_Call {
	return &MockOrderSagaStateRepository_TransitionStockStageToFailed_Call{Call: _e.mock.On("TransitionStockStageToFailed", ctx, orderID)}
}

func (_c *MockOrderSagaStateRepository_TransitionStockStageToFailed_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderSagaStateRepository_TransitionStockStageToFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderSagaStateRepository_TransitionStockStageToFailed_Call) Return(sagaState outbound.SagaState, err error) *MockOrderSagaStateRepository_TransitionStockStageToFailed_Call {
	_c.Call.Return(sagaState, err)
	return _c
}

func (_c *MockOrderSagaStateRepository_TransitionStockStageToFailed_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (outbound.SagaState, error)) *MockOrderSagaStateRepository_TransitionStockStageToFailed_Call {
	_c.Call.Return(run)
	return _c
}

// TransitionStockStageToRequested provides a mock function for the type MockOrderSagaStateRepository
func (_mock *MockOrderSagaStateRepository) TransitionStockStageToRequested(ctx context.Context, orderID uuid.UUID) (outbound.SagaState, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for TransitionStockStageToRequested")
	}

	var r0 outbound.SagaState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (outbound.SagaState, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) outbound.SagaState); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Get(0).(outbound.SagaState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderSagaStateRepository_TransitionStockStageToRequested_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransitionStockStageToRequested'
type MockOrderSagaStateRepository_TransitionStockStageToRequested_Call struct {
	*mock.Call
}

// TransitionStockStageToRequested is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderSagaStateRepository_Expecter) TransitionStockStageToRequested(ctx interface{}, orderID interface{}) *MockOrderSagaStateRepository_TransitionStockStageToRequested_Call {
	return &MockOrderSagaStateRepository_TransitionStockStageToRequested_Call{Call: _e.mock.On("TransitionStockStageToRequested", ctx, orderID)}
}

func (_c *MockOrderSagaStateRepository_TransitionStockStageToRequested_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderSagaStateRepository_TransitionStockStageToRequested_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderSagaStateRepository_TransitionStockStageToRequested_Call) Return(sagaState outbound.SagaState, err error) *MockOrderSagaStateRepository_TransitionStockStageToRequested_Call {
	_c.Call.Return(sagaState, err)
	return _c
}

func (_c *MockOrderSagaStateRepository_TransitionStockStageToRequested_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (outbound.SagaState, error)) *MockOrderSagaStateRepository_TransitionStockStageToRequested_Call {
	_c.Call.Return(run)
	return _c
}

// TransitionStockStageToSucceeded provides a mock function for the type MockOrderSagaStateRepository
func (_mock *MockOrderSagaStateRepository) TransitionStockStageToSucceeded(ctx context.Context, orderID uuid.UUID) (outbound.SagaState, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for TransitionStockStageToSucceeded")
	}

	var r0 outbound.SagaState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (outbound.SagaState, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) outbound.SagaState); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		r0 = ret.Get(0).(outbound.SagaState)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderSagaStateRepository_TransitionStockStageToSucceeded_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransitionStockStageToSucceeded'
type MockOrderSagaStateRepository_TransitionStockStageToSucceeded_Call struct {
	*mock.Call
}

// TransitionStockStageToSucceeded is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID uuid.UUID
func (_e *MockOrderSagaStateRepository_Expecter) TransitionStockStageToSucceeded(ctx interface{}, orderID interface{}) *MockOrderSagaStateRepository_TransitionStockStageToSucceeded_Call {
	return &MockOrderSagaStateRepository_TransitionStockStageToSucceeded_Call{Call: _e.mock.On("TransitionStockStageToSucceeded", ctx, orderID)}
}

func (_c *MockOrderSagaStateRepository_TransitionStockStageToSucceeded_Call) Run(run func(ctx context.Context, orderID uuid.UUID)) *MockOrderSagaStateRepository_TransitionStockStageToSucceeded_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderSagaStateRepository_TransitionStockStageToSucceeded_Call) Return(sagaState outbound.SagaState, err error) *MockOrderSagaStateRepository_TransitionStockStageToSucceeded_Call {
	_c.Call.Return(sagaState, err)
	return _c
}

func (_c *MockOrderSagaStateRepository_TransitionStockStageToSucceeded_Call) RunAndReturn(run func(ctx context.Context, orderID uuid.UUID) (outbound.SagaState, error)) *MockOrderSagaStateRepository_TransitionStockStageToSucceeded_Call {
	_c.Call.Return(run)
	return _c
}
