// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type PaymentStatus string

const (
	PaymentStatusInitiated  PaymentStatus = "initiated"
	PaymentStatusProcessing PaymentStatus = "processing"
	PaymentStatusSucceeded  PaymentStatus = "succeeded"
	PaymentStatusFailed     PaymentStatus = "failed"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}

	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus
	Valid         bool
}

func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}

	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}

	return string(ns.PaymentStatus), nil
}

type PaymentAttempt struct {
	PaymentAttemptID  uuid.UUID
	OrderID           uuid.UUID
	Status            PaymentStatus
	Amount            int64
	Currency          string
	ProviderName      string
	ProviderReference string
	IdempotencyKey    string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type OutboxRecord struct {
	ID            uuid.UUID
	EventID       uuid.UUID
	EventName     string
	AggregateType string
	AggregateID   string
	Topic         string
	Key           []byte
	Payload       []byte
	Headers       json.RawMessage
	Attempt       int32
	Status        interface{}
	LastError     sql.NullString
	NextAttemptAt time.Time
	LockedAt      sql.NullTime
	LockedBy      sql.NullString
	PublishedAt   sql.NullTime
	MaxAttempts   int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
