// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const appendOutboxRecord = `-- name: AppendOutboxRecord :one
INSERT INTO
  outbox_records (
    event_id,
    event_name,
    aggregate_type,
    aggregate_id,
    topic,
    key,
    payload,
    headers,
    status
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
  )
RETURNING
  id, event_id, event_name, aggregate_type, aggregate_id, topic, key, payload, headers, attempt, status, last_error, next_attempt_at, locked_at, locked_by, published_at, max_attempts, created_at, updated_at
`

type AppendOutboxRecordParams struct {
	EventID       uuid.UUID
	EventName     string
	AggregateType string
	AggregateID   string
	Topic         string
	Key           []byte
	Payload       []byte
	Headers       json.RawMessage
	Status        interface{}
}

func (q *Queries) AppendOutboxRecord(ctx context.Context, arg AppendOutboxRecordParams) (OutboxRecord, error) {
	row := q.db.QueryRowContext(ctx, appendOutboxRecord,
		arg.EventID,
		arg.EventName,
		arg.AggregateType,
		arg.AggregateID,
		arg.Topic,
		arg.Key,
		arg.Payload,
		arg.Headers,
		arg.Status,
	)
	var i OutboxRecord
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventName,
		&i.AggregateType,
		&i.AggregateID,
		&i.Topic,
		&i.Key,
		&i.Payload,
		&i.Headers,
		&i.Attempt,
		&i.Status,
		&i.LastError,
		&i.NextAttemptAt,
		&i.LockedAt,
		&i.LockedBy,
		&i.PublishedAt,
		&i.MaxAttempts,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimPendingOutboxRecords = `-- name: ClaimPendingOutboxRecords :many
WITH candidates AS (
  SELECT
    o.id
  FROM
    outbox_records AS o
  WHERE
    o.status = 'pending'
    AND o.next_attempt_at <= $3
  ORDER BY
    o.next_attempt_at,
    o.created_at,
    o.id
  LIMIT
    $4
  FOR UPDATE
    SKIP LOCKED
)
UPDATE outbox_records AS o
SET
  status = 'in_progress',
  locked_at = $1,
  locked_by = $2,
  updated_at = $1
FROM
  candidates
WHERE
  o.id = candidates.id
RETURNING
  o.id, o.event_id, o.event_name, o.aggregate_type, o.aggregate_id, o.topic, o.key, o.payload, o.headers, o.attempt, o.status, o.last_error, o.next_attempt_at, o.locked_at, o.locked_by, o.published_at, o.max_attempts, o.created_at, o.updated_at
`

type ClaimPendingOutboxRecordsParams struct {
	ClaimedAt  sql.NullTime
	LockedBy   sql.NullString
	Before     time.Time
	LimitCount int32
}

func (q *Queries) ClaimPendingOutboxRecords(ctx context.Context, arg ClaimPendingOutboxRecordsParams) ([]OutboxRecord, error) {
	rows, err := q.db.QueryContext(ctx, claimPendingOutboxRecords,
		arg.ClaimedAt,
		arg.LockedBy,
		arg.Before,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxRecord
	for rows.Next() {
		var i OutboxRecord
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventName,
			&i.AggregateType,
			&i.AggregateID,
			&i.Topic,
			&i.Key,
			&i.Payload,
			&i.Headers,
			&i.Attempt,
			&i.Status,
			&i.LastError,
			&i.NextAttemptAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.PublishedAt,
			&i.MaxAttempts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimStaleInProgressOutboxRecords = `-- name: ClaimStaleInProgressOutboxRecords :many
WITH candidates AS (
  SELECT
    o.id
  FROM
    outbox_records AS o
  WHERE
    o.status = 'in_progress'
    AND o.locked_at <= $3
  ORDER BY
    o.locked_at,
    o.created_at,
    o.id
  LIMIT
    $4
  FOR UPDATE
    SKIP LOCKED
)
UPDATE outbox_records AS o
SET
  locked_at = $1,
  locked_by = $2,
  updated_at = $1
FROM
  candidates
WHERE
  o.id = candidates.id
RETURNING
  o.id, o.event_id, o.event_name, o.aggregate_type, o.aggregate_id, o.topic, o.key, o.payload, o.headers, o.attempt, o.status, o.last_error, o.next_attempt_at, o.locked_at, o.locked_by, o.published_at, o.max_attempts, o.created_at, o.updated_at
`

type ClaimStaleInProgressOutboxRecordsParams struct {
	ClaimedAt   sql.NullTime
	LockedBy    sql.NullString
	StaleBefore sql.NullTime
	LimitCount  int32
}

func (q *Queries) ClaimStaleInProgressOutboxRecords(ctx context.Context, arg ClaimStaleInProgressOutboxRecordsParams) ([]OutboxRecord, error) {
	rows, err := q.db.QueryContext(ctx, claimStaleInProgressOutboxRecords,
		arg.ClaimedAt,
		arg.LockedBy,
		arg.StaleBefore,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OutboxRecord
	for rows.Next() {
		var i OutboxRecord
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EventName,
			&i.AggregateType,
			&i.AggregateID,
			&i.Topic,
			&i.Key,
			&i.Payload,
			&i.Headers,
			&i.Attempt,
			&i.Status,
			&i.LastError,
			&i.NextAttemptAt,
			&i.LockedAt,
			&i.LockedBy,
			&i.PublishedAt,
			&i.MaxAttempts,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxRecordPublished = `-- name: MarkOutboxRecordPublished :execrows
UPDATE outbox_records
SET
  status = 'published',
  published_at = $4,
  locked_at = NULL,
  locked_by = NULL,
  updated_at = $4
WHERE
  id = $1
  AND status = 'in_progress'
  AND locked_by = $2
  AND locked_at = $3
`

type MarkOutboxRecordPublishedParams struct {
	ID          uuid.UUID
	LockedBy    sql.NullString
	ClaimToken  sql.NullTime
	PublishedAt sql.NullTime
}

func (q *Queries) MarkOutboxRecordPublished(ctx context.Context, arg MarkOutboxRecordPublishedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOutboxRecordPublished, arg.ID, arg.LockedBy, arg.ClaimToken, arg.PublishedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markOutboxRecordRetryableFailure = `-- name: MarkOutboxRecordRetryableFailure :execrows
UPDATE outbox_records
SET
  status = 'pending',
  attempt = $4,
  next_attempt_at = $5,
  last_error = $6,
  locked_at = NULL,
  locked_by = NULL,
  updated_at = $7
WHERE
  id = $1
  AND status = 'in_progress'
  AND locked_by = $2
  AND locked_at = $3
`

type MarkOutboxRecordRetryableFailureParams struct {
	ID            uuid.UUID
	LockedBy      sql.NullString
	ClaimToken    sql.NullTime
	Attempt       int32
	NextAttemptAt time.Time
	LastError     sql.NullString
	UpdatedAt     time.Time
}

func (q *Queries) MarkOutboxRecordRetryableFailure(ctx context.Context, arg MarkOutboxRecordRetryableFailureParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOutboxRecordRetryableFailure,
		arg.ID,
		arg.LockedBy,
		arg.ClaimToken,
		arg.Attempt,
		arg.NextAttemptAt,
		arg.LastError,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markOutboxRecordDead = `-- name: MarkOutboxRecordDead :execrows
UPDATE outbox_records
SET
  status = 'dead',
  attempt = $4,
  next_attempt_at = $6,
  last_error = $5,
  locked_at = NULL,
  locked_by = NULL,
  updated_at = $6
WHERE
  id = $1
  AND status = 'in_progress'
  AND locked_by = $2
  AND locked_at = $3
`

type MarkOutboxRecordDeadParams struct {
	ID         uuid.UUID
	LockedBy   sql.NullString
	ClaimToken sql.NullTime
	Attempt    int32
	LastError  sql.NullString
	UpdatedAt  time.Time
}

func (q *Queries) MarkOutboxRecordDead(ctx context.Context, arg MarkOutboxRecordDeadParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markOutboxRecordDead,
		arg.ID,
		arg.LockedBy,
		arg.ClaimToken,
		arg.Attempt,
		arg.LastError,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
