// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payment_attempts.sql

package sqlc

import (
	"context"
)

const createInitiatedPaymentAttempt = `-- name: CreateInitiatedPaymentAttempt :one
INSERT INTO
  payment_attempts (
    order_id,
    status,
    amount,
    currency,
    provider_name,
    idempotency_key
  )
VALUES
  (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
  )
RETURNING
  payment_attempt_id, order_id, status, amount, currency, provider_name, provider_reference, idempotency_key, created_at, updated_at
`

type CreateInitiatedPaymentAttemptParams struct {
	OrderID        interface{}
	Status         interface{}
	Amount         int64
	Currency       string
	ProviderName   string
	IdempotencyKey string
}

func (q *Queries) CreateInitiatedPaymentAttempt(ctx context.Context, arg CreateInitiatedPaymentAttemptParams) (PaymentAttempt, error) {
	row := q.db.QueryRowContext(ctx, createInitiatedPaymentAttempt,
		arg.OrderID,
		arg.Status,
		arg.Amount,
		arg.Currency,
		arg.ProviderName,
		arg.IdempotencyKey,
	)
	var i PaymentAttempt
	err := row.Scan(
		&i.PaymentAttemptID,
		&i.OrderID,
		&i.Status,
		&i.Amount,
		&i.Currency,
		&i.ProviderName,
		&i.ProviderReference,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
